-- Move categories identify the type of attack a move is: physical, special, or status
MoveCategories = {
	NONE = 0,
	PHYSICAL = 1,
	SPECIAL = 2,
	STATUS = 3,
}

--List of pokemon types used to cycle through types when the Hidden Power button is clicked
HiddenPowerTypeList = {
	PokemonTypes.NORMAL,
	PokemonTypes.FIGHTING,
	PokemonTypes.FLYING,
	PokemonTypes.POISON,
	PokemonTypes.GROUND,
	PokemonTypes.ROCK,
	PokemonTypes.BUG,
	PokemonTypes.GHOST,
	PokemonTypes.STEEL,
	PokemonTypes.FIRE,
	PokemonTypes.WATER,
	PokemonTypes.GRASS,
	PokemonTypes.ELECTRIC,
	PokemonTypes.PSYCHIC,
	PokemonTypes.ICE,
	PokemonTypes.DRAGON,
	PokemonTypes.DARK
}

--Mapping of move types to move categories for gens 1-3
MoveTypeCategories = {
	[PokemonTypes.NORMAL] 	= MoveCategories.PHYSICAL,
	[PokemonTypes.FIGHTING]	= MoveCategories.PHYSICAL,
	[PokemonTypes.FLYING]	= MoveCategories.PHYSICAL,
	[PokemonTypes.POISON]	= MoveCategories.PHYSICAL,
	[PokemonTypes.GROUND]	= MoveCategories.PHYSICAL,
	[PokemonTypes.ROCK]		= MoveCategories.PHYSICAL,
	[PokemonTypes.BUG]		= MoveCategories.PHYSICAL,
	[PokemonTypes.GHOST]	= MoveCategories.PHYSICAL,
	[PokemonTypes.STEEL]	= MoveCategories.PHYSICAL,
	[PokemonTypes.FIRE]		= MoveCategories.SPECIAL,
	[PokemonTypes.WATER]	= MoveCategories.SPECIAL,
	[PokemonTypes.GRASS]	= MoveCategories.SPECIAL,
	[PokemonTypes.ELECTRIC]	= MoveCategories.SPECIAL,
	[PokemonTypes.PSYCHIC]	= MoveCategories.SPECIAL,
	[PokemonTypes.ICE]		= MoveCategories.SPECIAL,
	[PokemonTypes.DRAGON]	= MoveCategories.SPECIAL,
	[PokemonTypes.DARK]		= MoveCategories.SPECIAL,
}

NOPOWER = "---"
NOPP = ""

--[[
The various Pokémon moves (Gen 3)
Data pulled from Bulbapedia: https://bulbapedia.bulbagarden.net/wiki/List_of_moves (Note that categories differ from the source for Gen 3)

Format for an entry:

	id: string -> internal id of the move, represented as an integer in a string

	name: string -> the name of the move as it appears in game

	type: string -> the type of damage the move does, using the PokemonTypes enum

	power: string -> the strength of the move specified in game as in integer, or PLACEHOLDER when not applicable

	pp: string -> the base amount of actions this move is capable of

	accuracy: string -> the percent accuracy of the move connecting, or PLACEHOLDER when not applicable

	category: integer -> the type of damage a move does: physical/special/status, using the MoveCategories enum
]]
MoveData = {
	{ --- Empty entry for move ID 0
		id = "---",
		name = "---",
		type = PokemonTypes.UNKNOWN,
		power = NOPOWER,
		pp = NOPP,
		accuracy = PLACEHOLDER,
		category = MoveCategories.NONE,
		iscontact = false,
		priority = "0",
		summary = "",
	},
	{ -- Begin Gen 1 Moves
		id = "1",
		name = "Pound",
		type = PokemonTypes.NORMAL,
		power = "40",
		pp = "35",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has no secondary effect.",
	},
	{
		id = "2",
		name = "Karate Chop",
		type = PokemonTypes.FIGHTING,
		power = "50",
		pp = "25",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has an increased critical-hit ratio. (+1 stage = 1/8 or 12.5%)",
	},
	{
		id = "3",
		name = "DoubleSlap",
		type = PokemonTypes.NORMAL,
		power = "15",
		pp = "10",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Hits 2-5 times in one turn. Odds: 37.5% / 37.5% / 12.5% / 12.5%",
	},
	{
		id = "4",
		name = "Comet Punch",
		type = PokemonTypes.NORMAL,
		power = "18",
		pp = "15",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Hits 2-5 times in one turn. Odds: 37.5% / 37.5% / 12.5% / 12.5%",
	},
	{
		id = "5",
		name = "Mega Punch",
		type = PokemonTypes.NORMAL,
		power = "80",
		pp = "20",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has no secondary effect.",
	},
	{
		id = "6",
		name = "Pay Day",
		type = PokemonTypes.NORMAL,
		power = "40",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "Scatters coins equal to five times the user's level each time.",
	},
	{
		id = "7",
		name = "Fire Punch",
		type = PokemonTypes.FIRE,
		power = "75",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "Deals damage and has a 10% chance of burning the opponent.",
	},
	{
		id = "8",
		name = "Ice Punch",
		type = PokemonTypes.ICE,
		power = "75",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "Deals damage and has a 10% chance of freezing the opponent."
	},
	{
		id = "9",
		name = "ThunderPunch",
		type = PokemonTypes.ELECTRIC,
		power = "75",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "Deals damage and has a 10% chance of paralyzing the opponent.",
	},
	{
		id = "10",
		name = "Scratch",
		type = PokemonTypes.NORMAL,
		power = "40",
		pp = "35",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has no secondary effect.",
	},
	{
		id = "11",
		name = "ViceGrip",
		type = PokemonTypes.NORMAL,
		power = "55",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has no secondary effect.",
	},
	{
		id = "12",
		name = "Guillotine",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = "30",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "This move is 1% more accurate for each level above the target. Fails if target is higher level.",
	},
	{
		id = "13",
		name = "Razor Wind",
		type = PokemonTypes.NORMAL,
		power = "80",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "Does nothing on the turn it is selected. Deals damage on the following turn.",
	},
	{
		id = "14",
		name = "Swords Dance",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "30",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Increases the user's Attack stat by two stages.",
	},
	{
		id = "15",
		name = "Cut",
		type = PokemonTypes.NORMAL,
		power = "50",
		pp = "30",
		accuracy = "95",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has no secondary effect.",
	},
	{
		id = "16",
		name = "Gust",
		type = PokemonTypes.FLYING,
		power = "40",
		pp = "35",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "Deals double damage if opponent is using Fly or Bounce.",
	},
	{
		id = "17",
		name = "Wing Attack",
		type = PokemonTypes.FLYING,
		power = "60",
		pp = "35",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has no secondary effect.",
	},
	{
		id = "18",
		name = "Whirlwind",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.STATUS,
		priority = "-- 6",
		summary = "Forces target to switch out with another random Pokemon. Fails against Suction Cups or Ingrain.",
	},
	{
		id = "19",
		name = "Fly",
		type = PokemonTypes.FLYING,
		power = "70",
		pp = "15",
		accuracy = "95",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Attacks on 2nd turn. Can still be hit by Gust, Sky Uppercut, Thunder, Twister, and Whirlwind.",
	},
	{
		id = "20",
		name = "Bind",
		type = PokemonTypes.NORMAL,
		power = "15",
		pp = "20",
		accuracy = "75",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and inflicts 1/16 of the target's max HP as damage for 2-5 turns.",
	},
	{
		id = "21",
		name = "Slam",
		type = PokemonTypes.NORMAL,
		power = "80",
		pp = "20",
		accuracy = "75",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has no secondary effect.",
	},
	{
		id = "22",
		name = "Vine Whip",
		type = PokemonTypes.GRASS,
		power = "35",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "Deals damage and has no secondary effect.",
	},
	{
		id = "23",
		name = "Stomp",
		type = PokemonTypes.NORMAL,
		power = "65",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage with 30% chance of causing the target to flinch. Damage is doubled against a target that used Minimize.",
	},
	{
		id = "24",
		name = "Double Kick",
		type = PokemonTypes.FIGHTING,
		power = "30",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage twice, each hit able to be critical.",
	},
	{
		id = "25",
		name = "Mega Kick",
		type = PokemonTypes.NORMAL,
		power = "120",
		pp = "5",
		accuracy = "75",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has no secondary effect.",
	},
	{
		id = "26",
		name = "Jump Kick",
		type = PokemonTypes.FIGHTING,
		power = "70",
		pp = "25",
		accuracy = "95",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "If the move misses, the user is hurt for 1/2 of the damage it would have dealt.",
	},
	{
		id = "27",
		name = "Rolling Kick",
		type = PokemonTypes.FIGHTING,
		power = "60",
		pp = "15",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has a 30% chance of causing the target to flinch.",
	},
	{
		id = "28",
		name = "Sand-Attack",
		type = PokemonTypes.GROUND,
		power = NOPOWER,
		pp = "15",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Lowers the target's accuracy stat by one stage. (100% -> 75% -> 60% -> 50% ...)",
	},
	{
		id = "29",
		name = "Headbutt",
		type = PokemonTypes.NORMAL,
		power = "70",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has a 30% chance of causing the target to flinch.",
	},
	{
		id = "30",
		name = "Horn Attack",
		type = PokemonTypes.NORMAL,
		power = "65",
		pp = "25",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has no secondary effect.",
	},
	{
		id = "31",
		name = "Fury Attack",
		type = PokemonTypes.NORMAL,
		power = "15",
		pp = "20",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Hits 2-5 times in one turn. Odds: 37.5% / 37.5% / 12.5% / 12.5%",
	},
	{
		id = "32",
		name = "Horn Drill",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = "30",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "This move is 1% more accurate for each level above the target. Fails if target is higher level.",
	},
	{
		id = "33",
		name = "Tackle",
		type = PokemonTypes.NORMAL,
		power = "35",
		pp = "35",
		accuracy = "95",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has no secondary effect.",
	},
	{
		id = "34",
		name = "Body Slam",
		type = PokemonTypes.NORMAL,
		power = "85",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has a 30% chance of paralyzing the target.",
	},
	{
		id = "35",
		name = "Wrap",
		type = PokemonTypes.NORMAL,
		power = "15",
		pp = "20",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and inflicts 1/16 of the target's max HP as damage for 2-5 turns.",
	},
	{
		id = "36",
		name = "Take Down",
		type = PokemonTypes.NORMAL,
		power = "90",
		pp = "20",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "The user receives recoil damage equal to 1/4 of the damage dealt.",
	},
	{
		id = "37",
		name = "Thrash",
		type = PokemonTypes.NORMAL,
		power = "90",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage for 2-3 consecutive turns. User becomes confused afterwards.",
	},
	{
		id = "38",
		name = "Double-Edge",
		type = PokemonTypes.NORMAL,
		power = "120",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "The user receives recoil damage equal to 1/3 of the damage dealt.",
	},
	{
		id = "39",
		name = "Tail Whip",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "30",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Decreases the Defense stat of all adjacent opponents by one stage.",
	},
	{
		id = "40",
		name = "Poison Sting",
		type = PokemonTypes.POISON,
		power = "15",
		pp = "35",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage and has a 30% chance of poisoning the target.",
	},
	{
		id = "41",
		name = "Twineedle",
		type = PokemonTypes.BUG,
		power = "25",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage twice, each hit able to be critical. Final hit has a 20% chance of poisoning the target.",
	},
	{
		id = "42",
		name = "Pin Missile",
		type = PokemonTypes.BUG,
		power = "14",
		pp = "20",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
		summary = "Hits 2-5 times in one turn. Odds: 37.5% / 37.5% / 12.5% / 12.5%",
	},
	{
		id = "43",
		name = "Leer",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "30",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Decreases the Defense stat of all adjacent opponents by one stage.",
	},
	{
		id = "44",
		name = "Bite",
		type = PokemonTypes.DARK,
		power = "60",
		pp = "25",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "Deals damage and has a 30% chance of causing the target to flinch.",
	},
	{
		id = "45",
		name = "Growl",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "40",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Decreases the Attack stat of all adjacent opponents by one stage.",
	},
	{
		id = "46",
		name = "Roar",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.STATUS,
		priority = "-- 6",
		summary = "Forces target to switch out with another random Pokemon. Fails against Soundproof, Suction Cups or Ingrain.",
	},
	{
		id = "47",
		name = "Sing",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "15",
		accuracy = "55",
		category = MoveCategories.STATUS,
		summary = "Puts the target to sleep, lasts 2-5 turns. Fails against Insomnia, Vital Spirit or Soundproof.",
	},
	{
		id = "48",
		name = "Supersonic",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = "55",
		category = MoveCategories.STATUS,
		summary = "Causes the target to become confused. Fails against Soundproof or Own Tempo.",
	},
	{
		id = "49",
		name = "SonicBoom",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
		summary = "Always inflicts exactly 20 HP damage if it hits.",
	},
	{
		id = "50",
		name = "Disable",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = "55",
		category = MoveCategories.STATUS,
		summary = "Disables the last move used by the target for 2-5 turns.",
	},
	{
		id = "51",
		name = "Acid",
		type = PokemonTypes.POISON,
		power = "40",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage and has a 10% chance of lowering the target's Defense stat by one stage.",
	},
	{
		id = "52",
		name = "Ember",
		type = PokemonTypes.FIRE,
		power = "40",
		pp = "25",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 10% chance of burning the target.",
	},
	{
		id = "53",
		name = "Flamethrower",
		type = PokemonTypes.FIRE,
		power = "95",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 10% chance of burning the target.",
	},
	{
		id = "54",
		name = "Mist",
		type = PokemonTypes.ICE,
		power = NOPOWER,
		pp = "30",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "For five turns, enemy Pokemon cannot lower stats of Pokemon on your team.",
	},
	{
		id = "55",
		name = "Water Gun",
		type = PokemonTypes.WATER,
		power = "40",
		pp = "25",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has no secondary effect.",
	},
	{
		id = "56",
		name = "Hydro Pump",
		type = PokemonTypes.WATER,
		power = "120",
		pp = "5",
		accuracy = "80",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has no secondary effect.",
	},
	{
		id = "57",
		name = "Surf",
		type = PokemonTypes.WATER,
		power = "95",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Deals double damage if opponent is using Dive.",
	},
	{
		id = "58",
		name = "Ice Beam",
		type = PokemonTypes.ICE,
		power = "95",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 10% chance of freezing the target.",
	},
	{
		id = "59",
		name = "Blizzard",
		type = PokemonTypes.ICE,
		power = "120",
		pp = "5",
		accuracy = "70",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 10% chance of freezing the target.",
	},
	{
		id = "60",
		name = "Psybeam",
		type = PokemonTypes.PSYCHIC,
		power = "65",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 10% chance of confusing the target.",
	},
	{
		id = "61",
		name = "BubbleBeam",
		type = PokemonTypes.WATER,
		power = "65",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 10% chance of lowering the target's Speed stat by one stage.",
	},
	{
		id = "62",
		name = "Aurora Beam",
		type = PokemonTypes.ICE,
		power = "65",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 10% chance of lowering the target's Attack stat by one stage.",
	},
	{
		id = "63",
		name = "Hyper Beam",
		type = PokemonTypes.NORMAL,
		power = "150",
		pp = "5",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage and then forces the user to recharge during the next turn.",
	},
	{
		id = "64",
		name = "Peck",
		type = PokemonTypes.FLYING,
		power = "35",
		pp = "35",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has no secondary effect.",
	},
	{
		id = "65",
		name = "Drill Peck",
		type = PokemonTypes.FLYING,
		power = "80",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has no secondary effect.",
	},
	{
		id = "66",
		name = "Submission",
		type = PokemonTypes.FIGHTING,
		power = "80",
		pp = "25",
		accuracy = "80",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage, and the user receives recoil damage equal to 25% of the damage done.",
	},
	{
		id = "67",
		name = "Low Kick",
		type = PokemonTypes.FIGHTING,
		power = "WT",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals between 20-120 damage dependent on the weight of the target.",
	},
	{
		id = "68",
		name = "Counter",
		type = PokemonTypes.FIGHTING,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		priority = "-- 5",
		summary = "If hit by a Physical category move, deals twice the damage received back to the user.",
	},
	{
		id = "69",
		name = "Seismic Toss",
		type = PokemonTypes.FIGHTING,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals exact damage equal to the user's level.",
	},
	{
		id = "70",
		name = "Strength",
		type = PokemonTypes.NORMAL,
		power = "80",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has no secondary effect.",
	},
	{
		id = "71",
		name = "Absorb",
		type = PokemonTypes.GRASS,
		power = "20",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "50% of the damage dealt is restored to the user as HP.",
	},
	{
		id = "72",
		name = "Mega Drain",
		type = PokemonTypes.GRASS,
		power = "40",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "50% of the damage dealt is restored to the user as HP.",
	},
	{
		id = "73",
		name = "Leech Seed",
		type = PokemonTypes.GRASS,
		power = NOPOWER,
		pp = "10",
		accuracy = "90",
		category = MoveCategories.STATUS,
		summary = "Drains 1/8 of the target's HP at the end of each turn.",
	},
	{
		id = "74",
		name = "Growth",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "40",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Increases the user's Special Attack stat by one stage.",
	},
	{
		id = "75",
		name = "Razor Leaf",
		type = PokemonTypes.GRASS,
		power = "55",
		pp = "25",
		accuracy = "95",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has an increased critical-hit ratio. (+1 stage = 1/8 or 12.5%)",
	},
	{
		id = "76",
		name = "SolarBeam",
		type = PokemonTypes.GRASS,
		power = "120",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Attacks on the 2nd turn after use, or immediately in sunny weather. Half damage in rain.",
	},
	{
		id = "77",
		name = "PoisonPowder",
		type = PokemonTypes.POISON,
		power = NOPOWER,
		pp = "35",
		accuracy = "75",
		category = MoveCategories.STATUS,
		summary = "Poisons the target, losing 1/8 of the their max HP at the end of each turn.",
	},
	{
		id = "78",
		name = "Stun Spore",
		type = PokemonTypes.GRASS,
		power = NOPOWER,
		pp = "30",
		accuracy = "75",
		category = MoveCategories.STATUS,
		summary = "Paralyzes the target, reducing their Speed by 75%, and a 25% chance they will fail to act.",
	},
	{
		id = "79",
		name = "Sleep Powder",
		type = PokemonTypes.GRASS,
		power = NOPOWER,
		pp = "15",
		accuracy = "75",
		category = MoveCategories.STATUS,
		summary = "Puts the target to sleep, lasts 2-5 turns. Fails against Insomnia or Vital Spirit.",
	},
	{
		id = "80",
		name = "Petal Dance",
		type = PokemonTypes.GRASS,
		power = "70",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "Deals damage for 2-3 consecutive turns. User becomes confused afterwards.",
	},
	{
		id = "81",
		name = "String Shot",
		type = PokemonTypes.BUG,
		power = NOPOWER,
		pp = "40",
		accuracy = "95",
		category = MoveCategories.STATUS,
		summary = "Decreases the targets' Speed stat by one stage.",
	},
	{
		id = "82",
		name = "Dragon Rage",
		type = PokemonTypes.DRAGON,
		power = NOPOWER,
		pp = "10",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Always inflicts exactly 40 HP damage if it hits.",
	},
	{
		id = "83",
		name = "Fire Spin",
		type = PokemonTypes.FIRE,
		power = "15",
		pp = "15",
		accuracy = "70",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and inflicts 1/16 of the target's max HP as damage for 2-5 turns.",
	},
	{
		id = "84",
		name = "ThunderShock",
		type = PokemonTypes.ELECTRIC,
		power = "40",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 10% chance of paralyzing the target.",
	},
	{
		id = "85",
		name = "Thunderbolt",
		type = PokemonTypes.ELECTRIC,
		power = "95",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 10% chance of paralyzing the target.",
	},
	{
		id = "86",
		name = "Thunder Wave",
		type = PokemonTypes.ELECTRIC,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Paralyzes the target, reducing their Speed by 75%, and a 25% chance they will fail to act.",
	},
	{
		id = "87",
		name = "Thunder",
		type = PokemonTypes.ELECTRIC,
		power = "120",
		pp = "10",
		accuracy = "70",
		category = MoveCategories.SPECIAL,
		summary = "30% chance to paralyze. Can hit Fly and Bounce. Always hits during rain, 50% accuracy in sun.",
	},
	{
		id = "88",
		name = "Rock Throw",
		type = PokemonTypes.ROCK,
		power = "50",
		pp = "15",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage and has no secondary effect.",
	},
	{
		id = "89",
		name = "Earthquake",
		type = PokemonTypes.GROUND,
		power = "100",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "Deals double damage if opponent is using Dig.",
	},
	{
		id = "90",
		name = "Fissure",
		type = PokemonTypes.GROUND,
		power = NOPOWER,
		pp = "5",
		accuracy = "30",
		category = MoveCategories.PHYSICAL,
		summary = "This move is 1% more accurate for each level above the target. Fails if target is higher level. Can hit Pokemon using Dig.",
	},
	{
		id = "91",
		name = "Dig",
		type = PokemonTypes.GROUND,
		power = "60",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Attacks on 2nd turn. Can still be hit by Earthquake, Fissure, and Magnitude.",
	},
	{
		id = "92",
		name = "Toxic",
		type = PokemonTypes.POISON,
		power = NOPOWER,
		pp = "10",
		accuracy = "85",
		category = MoveCategories.STATUS,
		summary = "Poisons the target, losing increasing amounts of the their max HP at the end of each turn.",
	},
	{
		id = "93",
		name = "Confusion",
		type = PokemonTypes.PSYCHIC,
		power = "50",
		pp = "25",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 10% chance of confusing the target.",
	},
	{
		id = "94",
		name = "Psychic",
		type = PokemonTypes.PSYCHIC,
		power = "90",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 10% chance of lowering the target's Special Defense by one stage.",
	},
	{
		id = "95",
		name = "Hypnosis",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "20",
		accuracy = "60",
		category = MoveCategories.STATUS,
		summary = "Puts the target to sleep, lasts 2-5 turns. Fails against Insomnia or Vital Spirit.",
	},
	{
		id = "96",
		name = "Meditate",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "40",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Increases the user's Attack by one stage.",
	},
	{
		id = "97",
		name = "Agility",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "30",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Increases the user's Speed by two stages.",
	},
	{
		id = "98",
		name = "Quick Attack",
		type = PokemonTypes.NORMAL,
		power = "40",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		priority = "+ 1",
		summary = "This is an increased priority move, causing the user to attack before most other moves.",
	},
	{
		id = "99",
		name = "Rage",
		type = PokemonTypes.NORMAL,
		power = "20",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "When used consecutively, Attack stat increases by one stage when damaged by an attack.",
	},
	{
		id = "100",
		name = "Teleport",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Flees from wild Pokemon battles only. Fails if trapped by Block, Mean Look, Spider Web, or Ingrain.",
	},
	{
		id = "101",
		name = "Night Shade",
		type = PokemonTypes.GHOST,
		power = NOPOWER,
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "Deals exact damage equal to the user's level.",
	},
	{
		id = "102",
		name = "Mimic",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Copies the target's last used move. Fails against Sketch, Transform, Metronome, or a move already learned.",
	},
	{
		id = "103",
		name = "Screech",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "40",
		accuracy = "85",
		category = MoveCategories.STATUS,
		summary = "Decreases the target's Defense stat by two stat stages. Fails against Soundproof ability.",
	},
	{
		id = "104",
		name = "Double Team",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "15",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Increases the user's evasion by one stage.",
	},
	{
		id = "105",
		name = "Recover",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Restores up to 50% of the user's max HP.",
	},
	{
		id = "106",
		name = "Harden",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "30",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Increases the user's Defense stat by one stage.",
	},
	{
		id = "107",
		name = "Minimize",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Increases evasion by one stage. Will now receive x2 damage from Stomp, Astonish, Extrasensory, and Needle Arm.",
	},
	{
		id = "108",
		name = "SmokeScreen",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Lowers the target's accuracy stat by one stage. (100% -> 75% -> 60% -> 50% ...)",
	},
	{
		id = "109",
		name = "Confuse Ray",
		type = PokemonTypes.GHOST,
		power = NOPOWER,
		pp = "10",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Causes the target to become confused for 2-5 turns. 50% chance to damage self as a 40 power Physical move.",
	},
	{
		id = "110",
		name = "Withdraw",
		type = PokemonTypes.WATER,
		power = NOPOWER,
		pp = "40",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Increases the user's Defense by one stage.",
	},
	{
		id = "111",
		name = "Defense Curl",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "40",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Increases the user's Defense by one stage. Also doubles the power of user's Rollout and Ice Ball.",
	},
	{
		id = "112",
		name = "Barrier",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "30",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Increases the user's Defense by two stages.",
	},
	{
		id = "113",
		name = "Light Screen",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "30",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "For 5 turns, halves the damage done to user's team by Special moves.",
	},
	{
		id = "114",
		name = "Haze",
		type = PokemonTypes.ICE,
		power = NOPOWER,
		pp = "30",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Resets the stat stages of all active Pokemon on the field to 0.",
	},
	{
		id = "115",
		name = "Reflect",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "For 5 turns, halves the damage done to user's team by Physical moves.",
	},
	{
		id = "116",
		name = "Focus Energy",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "30",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Increases the user's critical hit ratio by two stages. (+2 stages = 1/4 or 25%)",
	},
	{
		id = "117",
		name = "Bide",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Endures attacks for two consectuive turns. Deals damage equal to twice the damage received.",
	},
	{
		id = "118",
		name = "Metronome",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Randomly selects a move to use, and a random target if necessary.",
	},
	{
		id = "119",
		name = "Mirror Move",
		type = PokemonTypes.FLYING,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Uses the last move targeted at the user by a Pokemon still on the field.",
	},
	{
		id = "120",
		name = "Selfdestruct",
		type = PokemonTypes.NORMAL,
		power = "200",
		pp = "5",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "The target's Defense is halved, effectively doubling the power of this move.",
	},
	{
		id = "121",
		name = "Egg Bomb",
		type = PokemonTypes.NORMAL,
		power = "100",
		pp = "10",
		accuracy = "75",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage and has no secondary effect.",
	},
	{
		id = "122",
		name = "Lick",
		type = PokemonTypes.GHOST,
		power = "20",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has a 30% chance of paralyzing the target.",
	},
	{
		id = "123",
		name = "Smog",
		type = PokemonTypes.POISON,
		power = "20",
		pp = "20",
		accuracy = "70",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage and has a 40% chance of poisoning the target.",
	},
	{
		id = "124",
		name = "Sludge",
		type = PokemonTypes.POISON,
		power = "65",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage and has a 30% chance of poisoning the target.",
	},
	{
		id = "125",
		name = "Bone Club",
		type = PokemonTypes.GROUND,
		power = "65",
		pp = "20",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage and has a 10% chance of causing the target to flinch.",
	},
	{
		id = "126",
		name = "Fire Blast",
		type = PokemonTypes.FIRE,
		power = "120",
		pp = "5",
		accuracy = "85",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 10% chance of burning the target.",
	},
	{
		id = "127",
		name = "Waterfall",
		type = PokemonTypes.WATER,
		power = "80",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "Deals damage and has no secondary effect.",
	},
	{
		id = "128",
		name = "Clamp",
		type = PokemonTypes.WATER,
		power = "35",
		pp = "10",
		accuracy = "75",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "Deals damage and inflicts 1/16 of the target's max HP as damage for 2-5 turns.",
	},
	{
		id = "129",
		name = "Swift",
		type = PokemonTypes.NORMAL,
		power = "60",
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage and bypasses accuracy checks to always hit, unless the target is in the semi-invulnerable turn of a move such as Dig or Fly.",
	},
	{
		id = "130",
		name = "Skull Bash",
		type = PokemonTypes.NORMAL,
		power = "100",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Raises the user's Defense by one stage. On the following turn, it deals damage.",
	},
	{
		id = "131",
		name = "Spike Cannon",
		type = PokemonTypes.NORMAL,
		power = "20",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "Hits 2-5 times in one turn. Odds: 37.5% / 37.5% / 12.5% / 12.5%",
	},
	{
		id = "132",
		name = "Constrict",
		type = PokemonTypes.NORMAL,
		power = "10",
		pp = "35",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has a 10% chance of lowering the target's Speed by one stage.",
	},
	{
		id = "133",
		name = "Amnesia",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Increases the user's Special Defense by two stages.",
	},
	{
		id = "134",
		name = "Kinesis",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "15",
		accuracy = "80",
		category = MoveCategories.STATUS,
		summary = "Lowers the target's accuracy stat by one stage. (100% -> 75% -> 60% -> 50% ...)",
	},
	{
		id = "135",
		name = "Softboiled",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Restores up to 50% of the user's max HP. Can be used outside of battle.",
	},
	{
		id = "136",
		name = "Hi Jump Kick",
		type = PokemonTypes.FIGHTING,
		power = "85",
		pp = "20",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "If the move misses, the user is hurt for 1/2 of the damage it would have dealt.",
	},
	{
		id = "137",
		name = "Glare",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "30",
		accuracy = "75",
		category = MoveCategories.STATUS,
		summary = "Paralyzes the target, reducing their Speed by 75%, and a 25% chance they will fail to act.",
	},
	{
		id = "138",
		name = "Dream Eater",
		type = PokemonTypes.PSYCHIC,
		power = "100",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Fails if target is not asleep. 50% of the damage dealt is restored to the user as HP.",
	},
	{
		id = "139",
		name = "Poison Gas",
		type = PokemonTypes.POISON,
		power = NOPOWER,
		pp = "40",
		accuracy = "55",
		category = MoveCategories.STATUS,
		summary = "Poisons the target, losing 1/8 of the their max HP at the end of each turn.",
	},
	{
		id = "140",
		name = "Barrage",
		type = PokemonTypes.NORMAL,
		power = "15",
		pp = "20",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
		summary = "Hits 2-5 times in one turn. Odds: 37.5% / 37.5% / 12.5% / 12.5%",
	},
	{
		id = "141",
		name = "Leech Life",
		type = PokemonTypes.BUG,
		power = "20",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "50% of the damage dealt is restored to the user as HP.",
	},
	{
		id = "142",
		name = "Lovely Kiss",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = "75",
		category = MoveCategories.STATUS,
		summary = "Puts the target to sleep, lasts 2-5 turns. Fails against Insomnia or Vital Spirit.",
	},
	{
		id = "143",
		name = "Sky Attack",
		type = PokemonTypes.FLYING,
		power = "140",
		pp = "5",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
		summary = "Attacks on 2nd turn, 30% chance to flinch target. Has increased critical-hit ratio. (+1 stage = 1/8 or 12.5%).",
	},
	{
		id = "144",
		name = "Transform",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Turns into the target, copying everything, even stat changes, except the current and max HP.",
	},
	{
		id = "145",
		name = "Bubble",
		type = PokemonTypes.WATER,
		power = "20",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 10% chance of lowering the target's Speed stat by one stage.",
	},
	{
		id = "146",
		name = "Dizzy Punch",
		type = PokemonTypes.NORMAL,
		power = "70",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has a 20% chance of confusing the target.",
	},
	{
		id = "147",
		name = "Spore",
		type = PokemonTypes.GRASS,
		power = NOPOWER,
		pp = "15",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Puts the target to sleep, lasts 2-5 turns. Fails against Insomnia or Vital Spirit.",
	},
	{
		id = "148",
		name = "Flash",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = "70",
		category = MoveCategories.STATUS,
		summary = "Lowers the target's accuracy stat by one stage. (100% -> 75% -> 60% -> 50% ...)",
	},
	{
		id = "149",
		name = "Psywave",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "15",
		accuracy = "80",
		category = MoveCategories.SPECIAL,
		summary = "Deals exact damage of a random amount between 50% and 150% of the user's level.",
	},
	{
		id = "150",
		name = "Splash",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "40",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Deals no damage and has no effect whatsoever.",
	},
	{
		id = "151",
		name = "Acid Armor",
		type = PokemonTypes.POISON,
		power = NOPOWER,
		pp = "40",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Increases the user's Defense by two stages.",
	},
	{
		id = "152",
		name = "Crabhammer",
		type = PokemonTypes.WATER,
		power = "90",
		pp = "10",
		accuracy = "85",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "Deals damage and has an increased critical-hit ratio. (+1 stage = 1/8 or 12.5%)",
	},
	{
		id = "153",
		name = "Explosion",
		type = PokemonTypes.NORMAL,
		power = "250",
		pp = "5",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "The target's Defense is halved, effectively doubling the power of this move.",
	},
	{
		id = "154",
		name = "Fury Swipes",
		type = PokemonTypes.NORMAL,
		power = "18",
		pp = "15",
		accuracy = "80",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Hits 2-5 times in one turn. Odds: 37.5% / 37.5% / 12.5% / 12.5%",
	},
	{
		id = "155",
		name = "Bonemerang",
		type = PokemonTypes.GROUND,
		power = "50",
		pp = "10",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage twice, each hit able to be critical.",
	},
	{
		id = "156",
		name = "Rest",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Restores HP to full while going to sleep for 2 turns. Fails if user has Insomnia or Vital Spirit.",
	},
	{
		id = "157",
		name = "Rock Slide",
		type = PokemonTypes.ROCK,
		power = "75",
		pp = "10",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage and has a 30% chance of causing each target to flinch.",
	},
	{
		id = "158",
		name = "Hyper Fang",
		type = PokemonTypes.NORMAL,
		power = "80",
		pp = "15",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has a 10% chance of causing the target to flinch.",
	},
	{
		id = "159",
		name = "Sharpen",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "30",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Increases the user's Attack stat by one stage.",
	},
	{
		id = "160",
		name = "Conversion",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "30",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Changes the user's type to match the type of one of the user's moves (including Conversion itself).",
	},
	{
		id = "161",
		name = "Tri Attack",
		type = PokemonTypes.NORMAL,
		power = "80",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage and has a 20% chance of either paralyzing, freezing, or burning the target.",
	},
	{
		id = "162",
		name = "Super Fang",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals exact damage equal to 50% of the target's current HP, minimum of 1.",
	},
	{
		id = "163",
		name = "Slash",
		type = PokemonTypes.NORMAL,
		power = "70",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has an increased critical-hit ratio. (+1 stage = 1/8 or 12.5%).",
	},
	{
		id = "164",
		name = "Substitute",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "User loses 25% of max HP to hide behind a substitute, which prevents the effects of most attacks.",
	},
	{
		id = "165",
		name = "Struggle",
		type = PokemonTypes.NORMAL,
		power = "50",
		pp = "1",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Hits as neutral damage, even through Wonder Guard. User receives recoil damage equal to 1/4 of damage dealt.",
	},
	{ -- Begin Gen 2 Moves
		id = "166",
		name = "Sketch",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "1",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "User learns the target's last move permanently, replacing Sketch in the process. Fails against some moves, or if user already knows the move.",
	},
	{
		id = "167",
		name = "Triple Kick",
		type = PokemonTypes.FIGHTING,
		power = "10",
		pp = "10",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage three times, each additional hit gains 10 power. Each hit has a separate accuracy check and is able to be critical.",
	},
	{
		id = "168",
		name = "Thief",
		type = PokemonTypes.DARK,
		power = "40",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "Steals the target's held item, if it has one. An item cannot be stolen if the target has Sticky Hold.",
	},
	{
		id = "169",
		name = "Spider Web",
		type = PokemonTypes.BUG,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Prevents the target from switching out or fleeing. A Pokemon can still flee if it has Run Away or holding a Smoke Ball.",
	},
	{
		id = "170",
		name = "Mind Reader",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Allows the next move used by the user to never miss, even against Bounce, Dig, Dive, and Fly.",
	},
	{
		id = "171",
		name = "Nightmare",
		type = PokemonTypes.GHOST,
		power = NOPOWER,
		pp = "15",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Causes a sleeping target to losing 1/4 of the their max HP at the end of each turn.",
	},
	{
		id = "172",
		name = "Flame Wheel",
		type = PokemonTypes.FIRE,
		power = "60",
		pp = "25",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "Deals damage and has a 10% chance of burning the target. This move will first thaw out its user if frozen.",
	},
	{
		id = "173",
		name = "Snore",
		type = PokemonTypes.NORMAL,
		power = "40",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "If the user is asleep, deals damage and has a 30% chance of causing the target to flinch. No effect against Soundproof.",
	},
	{
		id = "174",
		name = "Curse",
		type = PokemonTypes.UNKNOWN,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Lowers Speed but raises Attack and Defense. If user is Ghost, instead loses half max HP to curse target, causing them to lose 1/4 of the their max HP at end of each turn.",
	},
	{
		id = "175",
		name = "Flail",
		type = PokemonTypes.NORMAL,
		power = "<HP",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals more damage the less HP the user has. Important breakpoints: 80 power at 35% hp or lower, and 150 power at 10% hp or lower.",
	},
	{
		id = "176",
		name = "Conversion 2",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "30",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Randomly changes the user's type to a new type that resists or is immune to the type of the last damaging move it was hit by.",
	},
	{
		id = "177",
		name = "Aeroblast",
		type = PokemonTypes.FLYING,
		power = "100",
		pp = "5",
		accuracy = "95",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage and has an increased critical-hit ratio. (+1 stage = 1/8 or 12.5%)",
	},
	{
		id = "178",
		name = "Cotton Spore",
		type = PokemonTypes.GRASS,
		power = NOPOWER,
		pp = "40",
		accuracy = "85",
		category = MoveCategories.STATUS,
		summary = "Lowers the target's Speed stat by two stages.",
	},
	{
		id = "179",
		name = "Reversal",
		type = PokemonTypes.FIGHTING,
		power = "<HP",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals more damage the less HP the user has. Important breakpoints: 80 power at 35% hp or lower, and 150 power at 10% hp or lower.",
	},
	{
		id = "180",
		name = "Spite",
		type = PokemonTypes.GHOST,
		power = NOPOWER,
		pp = "10",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Decreases the PP of the target's last used move by 2-5 PP, chosen at random.",
	},
	{
		id = "181",
		name = "Powder Snow",
		type = PokemonTypes.ICE,
		power = "40",
		pp = "25",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 10% chance of freezing the target.",
	},
	{
		id = "182",
		name = "Protect",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		priority = "+ 3",
		summary = "Protects user from all effects of moves for the turn, including damage. Using this move consectuively halves its success rate each time.",
	},
	{
		id = "183",
		name = "Mach Punch",
		type = PokemonTypes.FIGHTING,
		power = "40",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		priority = "+ 1",
		summary = "This is an increased priority move, causing the user to attack before most other moves.",
	},
	{
		id = "184",
		name = "Scary Face",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = "90",
		category = MoveCategories.STATUS,
		summary = "Lowers the target's Speed stat by two stages.",
	},
	{
		id = "185",
		name = "Faint Attack", -- This is "Feint Attack" in gen 6+
		type = PokemonTypes.DARK,
		power = "60",
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and bypasses accuracy checks to always hit, unless the target is in the semi-invulnerable turn of a move such as Dig or Fly.",
	},
	{
		id = "186",
		name = "Sweet Kiss",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = "75",
		category = MoveCategories.STATUS,
		summary = "Causes the target to become confused for 2-5 turns. 50% chance to damage self as a 40 power Physical move.",
	},
	{
		id = "187",
		name = "Belly Drum",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "The user loses half of their max HP, and in return raises their Attack stat all the way to +6 stages.",
	},
	{
		id = "188",
		name = "Sludge Bomb",
		type = PokemonTypes.POISON,
		power = "90",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage and has a 30% chance of poisoning the target.",
	},
	{
		id = "189",
		name = "Mud-Slap",
		type = PokemonTypes.GROUND,
		power = "20",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage and lowers the target's accuracy by one stage.",
	},
	{
		id = "190",
		name = "Octazooka",
		type = PokemonTypes.WATER,
		power = "65",
		pp = "10",
		accuracy = "85",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 50% chance to lower the target's accuracy by one stage.",
	},
	{
		id = "191",
		name = "Spikes",
		type = PokemonTypes.GROUND,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Creates a hazard for the enemy team (can stack 3 times). Switching out deals 1/8, 1/6, or 1/4 max HP in damage to Pokemon without Flying or Levitate.",
	},
	{
		id = "192",
		name = "Zap Cannon",
		type = PokemonTypes.ELECTRIC,
		power = "100",
		pp = "5",
		accuracy = "50",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and paralyzes the target every time it hits.",
	},
	{
		id = "193",
		name = "Foresight",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "40",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Neutralizes accuracy checks against the target, and allows Fighting and Normal moves to hit them if they are Ghost.",
	},
	{
		id = "194",
		name = "Destiny Bond",
		type = PokemonTypes.GHOST,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "If the user faints as the result of a direct attack by an enemy, that Pokemon also faints. Effect ends when user uses another move.",
	},
	{
		id = "195",
		name = "Perish Song",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "All pokemon faint after 3 turns. Switching out or having Soundproof removes this effect.",
	},
	{
		id = "196",
		name = "Icy Wind",
		type = PokemonTypes.ICE,
		power = "55",
		pp = "15",
		accuracy = "95",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage to all adjacent opponents and lowers the Speed of each by one stage.",
	},
	{
		id = "197",
		name = "Detect",
		type = PokemonTypes.FIGHTING,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		priority = "+ 3",
		summary = "Protects user from all effects of moves for the turn, including damage. Using this move consectuively halves its success rate each time.",
	},
	{
		id = "198",
		name = "Bone Rush",
		type = PokemonTypes.GROUND,
		power = "25",
		pp = "10",
		accuracy = "80",
		category = MoveCategories.PHYSICAL,
		summary = "Hits 2-5 times in one turn. Odds: 37.5% / 37.5% / 12.5% / 12.5%",
	},
	{
		id = "199",
		name = "Lock-On",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Allows the next move used by the user to never miss, even against Bounce, Dig, Dive, and Fly.",
	},
	{
		id = "200",
		name = "Outrage",
		type = PokemonTypes.DRAGON,
		power = "90",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "Deals damage for 2-3 consecutive turns. User becomes confused afterwards.",
	},
	{
		id = "201",
		name = "Sandstorm",
		type = PokemonTypes.ROCK,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Changes weather to Sandstorm for 5 turns. Pokemon take 1/16 of their max HP in damage, except for Steel, Ground, and Rock types.",
	},
	{
		id = "202",
		name = "Giga Drain",
		type = PokemonTypes.GRASS,
		power = "60",
		pp = "5",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "50% of the damage dealt is restored to the user as HP.",
	},
	{
		id = "203",
		name = "Endure",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		priority = "+ 3",
		summary = "Allows the user to survive any single attack that would cause it to faint, leaving the user with 1 HP instead.",
	},
	{
		id = "204",
		name = "Charm",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Lowers the Attack stat of the target by two stages.",
	},
	{
		id = "205",
		name = "Rollout",
		type = PokemonTypes.ROCK,
		power = "30",
		pp = "20",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage over 5 turns, doubling in power each consectutive hit. Base power is doubled if the user had previously used Defense Curl.",
	},
	{
		id = "206",
		name = "False Swipe",
		type = PokemonTypes.NORMAL,
		power = "40",
		pp = "40",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage, but will always leave the target with 1 HP if it would otherwise cause it to faint.",
	},
	{
		id = "207",
		name = "Swagger",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "15",
		accuracy = "90",
		category = MoveCategories.STATUS,
		summary = "Raises the target's Attack stat by two stages and confuses it.",
	},
	{
		id = "208",
		name = "Milk Drink",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Restores up to 50% of the user's max HP. Can be used outside of battle.",
	},
	{
		id = "209",
		name = "Spark",
		type = PokemonTypes.ELECTRIC,
		power = "65",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "Deals damage and has a 30% chance of paralyzing the target.",
	},
	{
		id = "210",
		name = "Fury Cutter",
		type = PokemonTypes.BUG,
		power = "10",
		pp = "20",
		accuracy = "95",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Each time this move hits successively, its power will double, up to a maximum of 160. Otherwise, it resets to base power.",
	},
	{
		id = "211",
		name = "Steel Wing",
		type = PokemonTypes.STEEL,
		power = "70",
		pp = "25",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has a 10% chance of raising the user's Defense by one stage.",
	},
	{
		id = "212",
		name = "Mean Look",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Prevents the target from switching out or fleeing. A Pokemon can still flee if it has Run Away or holding a Smoke Ball.",
	},
	{
		id = "213",
		name = "Attract",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "15",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "If the user and the target are opposite genders, the target will become infatuated, unable to use moves 50% of the time.",
	},
	{
		id = "214",
		name = "Sleep Talk",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "If the user is asleep, randomly chooses another one of the user's moves to use.",
	},
	{
		id = "215",
		name = "Heal Bell",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Cures all Pokemon in the user's party of all status conditions. Fails against Pokemon with Soundproof.",
	},
	{
		id = "216",
		name = "Return",
		type = PokemonTypes.NORMAL,
		power = ">FR",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Power ranges between 0 (min friendship of 0) and 102 (max friendship of 255). If the user's friendship is 127 or less, Frustration is stronger.",
	},
	{
		id = "217",
		name = "Present",
		type = PokemonTypes.NORMAL,
		power = "RNG",
		pp = "15",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
		summary = "40% chance power is 40, 30% chance it's 80, 10% chance it's 120, and 20% chance to heal target by 1/4 their max HP.",
	},
	{
		id = "218",
		name = "Frustration",
		type = PokemonTypes.NORMAL,
		power = "<FR",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Power ranges between 102 (min friendship of 0) and 0 (max friendship of 255). If the user's friendship is 128 or greater, Return is stronger.",
	},
	{
		id = "219",
		name = "Safeguard",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "25",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "For 5 turns, protects the user's party from most status effects and confusion.",
	},
	{
		id = "220",
		name = "Pain Split",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Equalizes HP of user and target by adding both Pokemon's current HP together, then dividing by two, split among them evenly.",
	},
	{
		id = "221",
		name = "Sacred Fire",
		type = PokemonTypes.FIRE,
		power = "100",
		pp = "5",
		accuracy = "95",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 50% chance of burning the target. This move will first thaw out its user if frozen.",
	},
	{
		id = "222",
		name = "Magnitude",
		type = PokemonTypes.GROUND,
		power = "RNG",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "Power varies based on a random value and probability. Starting at value 4 and power 10, each additional value adds 20 power; 150 power at value 10. Can hit Pokemon using Dig.",
	},
	{
		id = "223",
		name = "DynamicPunch",
		type = PokemonTypes.FIGHTING,
		power = "100",
		pp = "5",
		accuracy = "50",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and always confuses the target, lasting 2-5 turns.",
	},
	{
		id = "224",
		name = "Megahorn",
		type = PokemonTypes.BUG,
		power = "120",
		pp = "10",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has no secondary effect.",
	},
	{
		id = "225",
		name = "DragonBreath",
		type = PokemonTypes.DRAGON,
		power = "60",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 30% chance of paralyzing the target.",
	},
	{
		id = "226",
		name = "Baton Pass",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "40",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Switches out the user, passing all temporary stat stage changes as well as many other effects and conditions, on to the Pokemon that replaces it in battle.",
	},
	{
		id = "227",
		name = "Encore",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Prevents the target from using any move except its last used move, lasts for 2-6 turns.",
	},
	{
		id = "228",
		name = "Pursuit",
		type = PokemonTypes.DARK,
		power = "40",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "If the target Pokemon attempts to switch out, Pursuit's power will double and hit it first.",
	},
	{
		id = "229",
		name = "Rapid Spin",
		type = PokemonTypes.NORMAL,
		power = "20",
		pp = "40",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and removes the effects of any binding moves, Leech Seed, and any entry hazards such as Spikes from the user's field.",
	},
	{
		id = "230",
		name = "Sweet Scent",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Lowers the evasion of all adjacent opponents by one stage.",
	},
	{
		id = "231",
		name = "Iron Tail",
		type = PokemonTypes.STEEL,
		power = "100",
		pp = "15",
		accuracy = "75",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has a 30% chance of lowering the target's Defense stat by one stage.",
	},
	{
		id = "232",
		name = "Metal Claw",
		type = PokemonTypes.STEEL,
		power = "50",
		pp = "35",
		accuracy = "95",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has a 10% chance of raising the user's Attack stat by one stage.",
	},
	{
		id = "233",
		name = "Vital Throw",
		type = PokemonTypes.FIGHTING,
		power = "70",
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		priority = "-- 1",
		summary = "This is a decreased priority move, causing the user to attack after most other moves.",
	},
	{
		id = "234",
		name = "Morning Sun",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Restores the user's HP by a percentage based weather: 1/2 in no weather, 2/3 if sunny, and 1/4 during any other weather condition.",
	},
	{
		id = "235",
		name = "Synthesis",
		type = PokemonTypes.GRASS,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Restores the user's HP by a percentage based weather: 1/2 in no weather, 2/3 if sunny, and 1/4 during any other weather condition.",
	},
	{
		id = "236",
		name = "Moonlight",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Restores the user's HP by a percentage based weather: 1/2 in no weather, 2/3 if sunny, and 1/4 during any other weather condition.",
	},
	{
		id = "237",
		name = "Hidden Power",
		type = PokemonTypes.NORMAL,
		power = "VAR",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "Power varies between 30 and 70. Type is dependent on IVs, but Fighting type for most enemy Pokemon. Regardless of type, it can be Countered by not Mirror Coat.",
	},
	{
		id = "238",
		name = "Cross Chop",
		type = PokemonTypes.FIGHTING,
		power = "100",
		pp = "5",
		accuracy = "80",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has an increased critical-hit ratio. (+1 stage = 1/8 or 12.5%)",
	},
	{
		id = "239",
		name = "Twister",
		type = PokemonTypes.DRAGON,
		power = "40",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 20% chance of causing each target to flinch. Hits Pokemon using Bounce or Fly for double damage.",
	},
	{
		id = "240",
		name = "Rain Dance",
		type = PokemonTypes.WATER,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Changes weather to Rain for 5 turns. Water moves boosted by 50% and Fire moves weakened by 50%. Thunder ignores accuracy and evasion.",
	},
	{
		id = "241",
		name = "Sunny Day",
		type = PokemonTypes.FIRE,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Changes weather to Sunny for 5 turns. Fire moves boosted by 50% and Water moves weakened by 50%. Thunder accuracy becomes 50%.",
	},
	{
		id = "242",
		name = "Crunch",
		type = PokemonTypes.DARK,
		power = "80",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "Deals damage and has a 20% chance of lowering the target's Special Defense stat by one stage.",
	},
	{
		id = "243",
		name = "Mirror Coat",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		priority = "-- 5",
		summary = "If hit by a Special category move, deals twice the damage received back to the user.",
	},
	{
		id = "244",
		name = "Psych Up",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Resets the user's stat changes and copies all of the target's stat stages onto the user: ATK DEF SPA SPD SPE ACC EVA.",
	},
	{
		id = "245",
		name = "ExtremeSpeed",
		type = PokemonTypes.NORMAL,
		power = "80",
		pp = "5",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		priority = "+ 1",
		summary = "This is an increased priority move, causing the user to attack before most other moves.",
	},
	{
		id = "246",
		name = "AncientPower",
		type = PokemonTypes.ROCK,
		power = "60",
		pp = "5",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has a 10% chance of raising the user's Attack, Defense, Special Attack, Special Defense, and Speed by one stage each.",
	},
	{
		id = "247",
		name = "Shadow Ball",
		type = PokemonTypes.GHOST,
		power = "80",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage and has a 20% chance of lowering the target's Special Defense by one stage.",
	},
	{
		id = "248",
		name = "Future Sight",
		type = PokemonTypes.PSYCHIC,
		power = "80",
		pp = "15",
		accuracy = "90",
		category = MoveCategories.SPECIAL,
		summary = "Locks in damage when used based on SpAtk of user and SpDef of target. After 2 turns, deals damage to the current enemy. Attack is typeless: cannot STAB, hits Wonder Guard.",
	},
	{
		id = "249",
		name = "Rock Smash",
		type = PokemonTypes.FIGHTING,
		power = "20",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has a 50% chance of lowering the target's Defense stat by one stage.",
	},
	{
		id = "250",
		name = "Whirlpool",
		type = PokemonTypes.WATER,
		power = "15",
		pp = "15",
		accuracy = "70",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and inflicts 1/16 of the target's max HP as damage for 2-5 turns. Deals double damage if opponent is using Dive.",
	},
	{
		id = "251",
		name = "Beat Up",
		type = PokemonTypes.DARK,
		power = "10",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Each conscious, non-statused Pokemon in the user's party does an independent attack, each one is typeless with power of 10.",
	},
	{ -- Begin Gen 3 Moves
		id = "252",
		name = "Fake Out",
		type = PokemonTypes.NORMAL,
		power = "40",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		priority = "+ 1",
		summary = "This is an increased priority move. It always makes the target flinch, but attack will fail if it's not the first move used.",
	},
	{
		id = "253",
		name = "Uproar",
		type = PokemonTypes.NORMAL,
		power = "50",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage for 2-5 consecutive turns. Wakes up sleeping Pokemon and prevents them from falling asleep, except those with Soundproof.",
	},
	{
		id = "254",
		name = "Stockpile",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Stores up energy, stacks three times. Unleash energy using Spit Up to deal damage or Swallow to heal HP.",
	},
	{
		id = "255",
		name = "Spit Up",
		type = PokemonTypes.NORMAL,
		power = "100x",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "Consumes energy stored up by Stockpile, 100 power for each stack (0 if none). This move cannot cause a critical hit.",
	},
	{
		id = "256",
		name = "Swallow",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Consumes energy stored up by Stockpile, healing user for 25%, 50%, or 100% HP based on number of stacks consumed (0% if none).",
	},
	{
		id = "257",
		name = "Heat Wave",
		type = PokemonTypes.FIRE,
		power = "100",
		pp = "10",
		accuracy = "90",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 10% chance of burning the target.",
	},
	{
		id = "258",
		name = "Hail",
		type = PokemonTypes.ICE,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Changes weather to Hail for 5 turns. Pokemon take 1/16 of their max HP in damage, except for Ice types.",
	},
	{
		id = "259",
		name = "Torment",
		type = PokemonTypes.DARK,
		power = NOPOWER,
		pp = "15",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Prevents the target from choosing to use the same move twice in a row. Effect ends when the Pokemon switches out.",
	},
	{
		id = "260",
		name = "Flatter",
		type = PokemonTypes.DARK,
		power = NOPOWER,
		pp = "15",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Raises the target's Special Attack stat by one stage and confuses it.",
	},
	{
		id = "261",
		name = "Will-O-Wisp",
		type = PokemonTypes.FIRE,
		power = NOPOWER,
		pp = "15",
		accuracy = "75",
		category = MoveCategories.STATUS,
		summary = "Inflicts a burn on the target, ineffective against Fire type Pokemon. Burned Pokemon deal half damage with Physical moves and lose 1/8 max HP each turn.",
	},
	{
		id = "262",
		name = "Memento",
		type = PokemonTypes.DARK,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "User faints to lower the Attack and Special Attack stat of the target by two stages each.",
	},
	{
		id = "263",
		name = "Facade",
		type = PokemonTypes.NORMAL,
		power = "70",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Power doubles if the user is poisoned, paralyzed, or burned.",
	},
	{
		id = "264",
		name = "Focus Punch",
		type = PokemonTypes.FIGHTING,
		power = "150",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		priority = "-- 3",
		summary = "This is a decreased priority move. This move will fail if the user is dealt direct damage first.",
	},
	{
		id = "265",
		name = "SmellingSalt",
		type = PokemonTypes.NORMAL,
		power = "60",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Power doubles against a paralyzed target, but it will also cure the target of paralysis.",
	},
	{
		id = "266",
		name = "Follow Me",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		priority = "+ 3",
		summary = "This is an increased priority move. The user redirects all targeted moves by enemy Pokemon to itself.",
	},
	{
		id = "267",
		name = "Nature Power",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Sand: Earthquake, Building: Swift, Cave: Shadow Ball, Rock: Rock Slide, Tall grass: Stun Spore, Long grass: Razor Leaf, Pond: Bubblebeam, Sea: Surf, Underwater: Hydro Pump.",
	},
	{
		id = "268",
		name = "Charge",
		type = PokemonTypes.ELECTRIC,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "User charges up, doubling the damage dealt by the next move it uses but only for Electric moves.",
	},
	{
		id = "269",
		name = "Taunt",
		type = PokemonTypes.DARK,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Prevents the target Pokemon from using Status category moves: any move that isn't Physical or Special.",
	},
	{
		id = "270",
		name = "Helping Hand",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		priority = "+ 5",
		summary = "This is an increased priority move. The user boost its ally's damage done by 50% for this turn only.",
	},
	{
		id = "271",
		name = "Trick",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "10",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Switches held items with the target. This move fails if neither Pokemon are holding an item, or in a battle with a wild Pokemon.",
	},
	{
		id = "272",
		name = "Role Play",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Replaces the user's ability with the target's. Fails if target ability is Trace or Wonder Guard. Some abilities like Intimidate don't trigger.",
	},
	{
		id = "273",
		name = "Wish",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "No effect on the turn used. At the end of the next turn, the Pokemon in the user's current position will be healed by half its own max HP.",
	},
	{
		id = "274",
		name = "Assist",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Randomly selects an eligible move from all other moves known by Pokemon in the user's party, including fainted Pokemon.",
	},
	{
		id = "275",
		name = "Ingrain",
		type = PokemonTypes.GRASS,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Restore 1/16th of its max HP at the end of every turn. Prevents the user from switching out, even from moves like Roar and Whirlwind.",
	},
	{
		id = "276",
		name = "Superpower",
		type = PokemonTypes.FIGHTING,
		power = "120",
		pp = "5",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage, then lowers the user's Attack and Defense stats by one stage each.",
	},
	{
		id = "277",
		name = "Magic Coat",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "15",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		priority = "+ 4",
		summary = "Reflects most Status category moves back at the enemy, most offensive moves that aren't Physical or Special.",
	},
	{
		id = "278",
		name = "Recycle",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Regains a held item, such as a Berry. Fails if item was lost through Thief or Knock Off.",
	},
	{
		id = "279",
		name = "Revenge",
		type = PokemonTypes.FIGHTING,
		power = "60",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		priority = "-- 4",
		summary = "This is a decreased priority move. Power is doubled if user is damaged by the target in the same turn.",
	},
	{
		id = "280",
		name = "Brick Break",
		type = PokemonTypes.FIGHTING,
		power = "75",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Removes Light Screen and Reflect from the opponent's side of the field, then inflicts damage. Removes those effects even against Ghost Pokemon.",
	},
	{
		id = "281",
		name = "Yawn",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Makes the target drowsy. At the end of the next turn, the drowsy Pokemon will fall asleep.",
	},
	{
		id = "282",
		name = "Knock Off",
		type = PokemonTypes.DARK,
		power = "20",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "Renders the target's held item unusable for the rest of the battle, even if switches out.",
	},
	{
		id = "283",
		name = "Endeavor",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Causes the target's HP to become equal the user's current HP.",
	},
	{
		id = "284",
		name = "Eruption",
		type = PokemonTypes.FIRE,
		power = ">HP",
		pp = "5",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Has 150 power at max HP, but its power decreases proportionally to the user's remaining HP. Formula: 150 x currHP / maxHP",
	},
	{
		id = "285",
		name = "Skill Swap",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Exchanges the abilities of the user and the target. This information is not shown to the player. Fails against Wonder Guard.",
	},
	{
		id = "286",
		name = "Imprison",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "As long as the user remains in battle, opponents cannot use any move which is also known by the user.",
	},
	{
		id = "287",
		name = "Refresh",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Cures the user of burns, poison, or paralysis. It cannot cure sleep if it is used by Sleep Talk.",
	},
	{
		id = "288",
		name = "Grudge",
		type = PokemonTypes.GHOST,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "If the user faints as the result of a direct attack by an enemy, the last used move loses all PP. Effect ends when user uses another move.",
	},
	{
		id = "289",
		name = "Snatch",
		type = PokemonTypes.DARK,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		priority = "+ 4",
		summary = "This is an increased priority move. If another Pokemon tries to use a beneficial Status category move, the user will use that move instead.",
	},
	{
		id = "290",
		name = "Secret Power",
		type = PokemonTypes.NORMAL,
		power = "70",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "30% chance to Sand: --ACC, Building: paralysis, Cave: flinch, Rock: confusion, Tall grass: poison, Long grass: sleep, Pond: --SPD, Sea: --ATK, Underwater: --DEF",
	},
	{
		id = "291",
		name = "Dive",
		type = PokemonTypes.WATER,
		power = "60",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "Attacks on 2nd turn. Can still be hit by Surf and Whirlpool and will take double damage.",
	},
	{
		id = "292",
		name = "Arm Thrust",
		type = PokemonTypes.FIGHTING,
		power = "15",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Hits 2-5 times in one turn. Odds: 37.5% / 37.5% / 12.5% / 12.5%",
	},
	{
		id = "293",
		name = "Camouflage",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Change user's type based on terrain. Building: Normal, Sand: Ground, Cave/rock: Rock, Tall/long grass: Grass, Water: Water",
	},
	{
		id = "294",
		name = "Tail Glow",
		type = PokemonTypes.BUG,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Increases the user's Special Attack by two stages.",
	},
	{
		id = "295",
		name = "Luster Purge",
		type = PokemonTypes.PSYCHIC,
		power = "70",
		pp = "5",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 50% chance of lowering the target's Special Defense.",
	},
	{
		id = "296",
		name = "Mist Ball",
		type = PokemonTypes.PSYCHIC,
		power = "70",
		pp = "5",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 50% chance of lowering the target's Special Attack.",
	},
	{
		id = "297",
		name = "FeatherDance",
		type = PokemonTypes.FLYING,
		power = NOPOWER,
		pp = "15",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Lowers the target's Attack stat by two stages.",
	},
	{
		id = "298",
		name = "Teeter Dance",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Causes all other Pokemon to become confused for 2-5 turns. 50% chance to damage self as a 40 power Physical move.",
	},
	{
		id = "299",
		name = "Blaze Kick",
		type = PokemonTypes.FIRE,
		power = "85",
		pp = "10",
		accuracy = "90",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "Deals damage and has a 10% chance of burning the target. It also has an increased critical hit ratio. (+1 stage = 1/8 or 12.5%)",
	},
	{
		id = "300",
		name = "Mud Sport",
		type = PokemonTypes.GROUND,
		power = NOPOWER,
		pp = "15",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Reduces the power of Electric moves by 50% for all Pokemon in the battle. This effect last until the user switches out.",
	},
	{
		id = "301",
		name = "Ice Ball",
		type = PokemonTypes.ICE,
		power = "30",
		pp = "20",
		accuracy = "90",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "Deals damage over 5 turns, doubling in power each consectutive hit. Base power is doubled if the user had previously used Defense Curl.",
	},
	{
		id = "302",
		name = "Needle Arm",
		type = PokemonTypes.GRASS,
		power = "60",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "Deals damage and has a 30% chance of causing the target to flinch. Damage is doubled against a target that used Minimize.",
	},
	{
		id = "303",
		name = "Slack Off",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Restores up to 50% of the user's max HP.",
	},
	{
		id = "304",
		name = "Hyper Voice",
		type = PokemonTypes.NORMAL,
		power = "90",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage to all adjacent opponents. Pokemon with Soundproof are not affected by this move.",
	},
	{
		id = "305",
		name = "Poison Fang",
		type = PokemonTypes.POISON,
		power = "50",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has a 30% chance of badly poisoning the target.",
	},
	{
		id = "306",
		name = "Crush Claw",
		type = PokemonTypes.NORMAL,
		power = "75",
		pp = "10",
		accuracy = "95",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has a 50% chance of lowering the target's Defense stat by one stage.",
	},
	{
		id = "307",
		name = "Blast Burn",
		type = PokemonTypes.FIRE,
		power = "150",
		pp = "5",
		accuracy = "90",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and then forces the user to recharge during the next turn.",
	},
	{
		id = "308",
		name = "Hydro Cannon",
		type = PokemonTypes.WATER,
		power = "150",
		pp = "5",
		accuracy = "90",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and then forces the user to recharge during the next turn.",
	},
	{
		id = "309",
		name = "Meteor Mash",
		type = PokemonTypes.STEEL,
		power = "100",
		pp = "10",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has a 20% chance of raising the user's Attack stat by one stage.",
	},
	{
		id = "310",
		name = "Astonish",
		type = PokemonTypes.GHOST,
		power = "30",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has a 30% chance of causing the target to flinch. Damage is doubled against a target that used Minimize.",
	},
	{
		id = "311",
		name = "Weather Ball",
		type = PokemonTypes.NORMAL,
		power = "50",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "Power doubles in weather and changes type: Fire if sunny, Water if raining, Ice if hailing, Rock if sandstorm.",
	},
	{
		id = "312",
		name = "Aromatherapy",
		type = PokemonTypes.GRASS,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Cures all Pokemon in the user's party of all status conditions.",
	},
	{
		id = "313",
		name = "Fake Tears",
		type = PokemonTypes.DARK,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Lowers the target's Special Defense stat by two stages.",
	},
	{
		id = "314",
		name = "Air Cutter",
		type = PokemonTypes.FLYING,
		power = "55",
		pp = "25",
		accuracy = "95",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage and has an increased critical hit ratio. (+1 stage = 1/8 or 12.5%)",
	},
	{
		id = "315",
		name = "Overheat",
		type = PokemonTypes.FIRE,
		power = "140",
		pp = "5",
		accuracy = "90",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "Deals damage and lowers the user's Special Attack by two stages.",
	},
	{
		id = "316",
		name = "Odor Sleuth",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "40",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Neutralizes accuracy checks against the target, and allows Fighting and Normal moves to hit them if they are Ghost.",
	},
	{
		id = "317",
		name = "Rock Tomb",
		type = PokemonTypes.ROCK,
		power = "50",
		pp = "10",
		accuracy = "80",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage and lowers the opponent's Speed by one stage.",
	},
	{
		id = "318",
		name = "Silver Wind",
		type = PokemonTypes.BUG,
		power = "60",
		pp = "5",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage and has a 10% chance of raising the user's Attack, Defense, Special Attack, Special Defense, and Speed by one stage each.",
	},
	{
		id = "319",
		name = "Metal Sound",
		type = PokemonTypes.STEEL,
		power = NOPOWER,
		pp = "40",
		accuracy = "85",
		category = MoveCategories.STATUS,
		summary = "Deals lowers the target's Special Defense stat by two stages. Fails against Pokemon with Soundproof.",
	},
	{
		id = "320",
		name = "GrassWhistle",
		type = PokemonTypes.GRASS,
		power = NOPOWER,
		pp = "15",
		accuracy = "55",
		category = MoveCategories.STATUS,
		summary = "Puts the target to sleep, lasts 2-5 turns. Fails against Insomnia, Vital Spirit, or Soundproof.",
	},
	{
		id = "321",
		name = "Tickle",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.STATUS,
		summary = "Reduces the target's Attack and Defense stats by one stage each. Works even if enemy has a Substitute.",
	},
	{
		id = "322",
		name = "Cosmic Power",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Raises the Defense and Special Defense of the user by one stage each.",
	},
	{
		id = "323",
		name = "Water Spout",
		type = PokemonTypes.WATER,
		power = ">HP",
		pp = "5",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Has 150 power at max HP, but its power decreases proportionally to the user's remaining HP. Formula: 150 x currHP / maxHP",
	},
	{
		id = "324",
		name = "Signal Beam",
		type = PokemonTypes.BUG,
		power = "75",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage and has a 10% chance of confusing the target.",
	},
	{
		id = "325",
		name = "Shadow Punch",
		type = PokemonTypes.GHOST,
		power = "60",
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and bypasses accuracy checks to always hit, unless the target is in the semi-invulnerable turn of a move such as Dig or Fly.",
	},
	{
		id = "326",
		name = "Extrasensory",
		type = PokemonTypes.PSYCHIC,
		power = "80",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 10% chance of causing the target to flinch. Damage is doubled against a target that used Minimize.",
	},
	{
		id = "327",
		name = "Sky Uppercut",
		type = PokemonTypes.FIGHTING,
		power = "85",
		pp = "15",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and can hit Pokemon during the semi-invulnerable turns of Fly and Bounce.",
	},
	{
		id = "328",
		name = "Sand Tomb",
		type = PokemonTypes.GROUND,
		power = "15",
		pp = "15",
		accuracy = "70",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage and inflicts 1/16 of the target's max HP as damage for 2-5 turns.",
	},
	{
		id = "329",
		name = "Sheer Cold",
		type = PokemonTypes.ICE,
		power = NOPOWER,
		pp = "5",
		accuracy = "30",
		category = MoveCategories.SPECIAL,
		summary = "This move is 1% more accurate for each level above the target. Fails if target is higher level.",
	},
	{
		id = "330",
		name = "Muddy Water",
		type = PokemonTypes.WATER,
		power = "95",
		pp = "10",
		accuracy = "85",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 30% chance of lowering each target's accuracy by one stage.",
	},
	{
		id = "331",
		name = "Bullet Seed",
		type = PokemonTypes.GRASS,
		power = "10",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Hits 2-5 times in one turn. Odds: 37.5% / 37.5% / 12.5% / 12.5%",
	},
	{
		id = "332",
		name = "Aerial Ace",
		type = PokemonTypes.FLYING,
		power = "60",
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and bypasses accuracy checks to always hit, unless the target is in the semi-invulnerable turn of a move such as Dig or Fly.",
	},
	{
		id = "333",
		name = "Icicle Spear",
		type = PokemonTypes.ICE,
		power = "10",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Hits 2-5 times in one turn. Odds: 37.5% / 37.5% / 12.5% / 12.5%",
	},
	{
		id = "334",
		name = "Iron Defense",
		type = PokemonTypes.STEEL,
		power = NOPOWER,
		pp = "15",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Deals raises the user's Defense stat by two stages.",
	},
	{
		id = "335",
		name = "Block",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Prevents the target from switching out or fleeing. A Pokemon can still flee if it has Run Away or holding a Smoke Ball.",
	},
	{
		id = "336",
		name = "Howl",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "40",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Deals raises the user's Attack stat by one stage.",
	},
	{
		id = "337",
		name = "Dragon Claw",
		type = PokemonTypes.DRAGON,
		power = "80",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "Deals damage and has no secondary effect.",
	},
	{
		id = "338",
		name = "Frenzy Plant",
		type = PokemonTypes.GRASS,
		power = "150",
		pp = "5",
		accuracy = "90",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and then forces the user to recharge during the next turn.",
	},
	{
		id = "339",
		name = "Bulk Up",
		type = PokemonTypes.FIGHTING,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Raises the user's Attack stat and Defense stat by one stage each.",
	},
	{
		id = "340",
		name = "Bounce",
		type = PokemonTypes.FLYING,
		power = "85",
		pp = "5",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Attacks on 2nd turn. Can still be hit by Gust, Sky Uppercut, Thunder, and Twister.",
	},
	{
		id = "341",
		name = "Mud Shot",
		type = PokemonTypes.GROUND,
		power = "55",
		pp = "15",
		accuracy = "95",
		category = MoveCategories.PHYSICAL,
		summary = "Deals damage and then lowers the target's Speed stat by one stage.",
	},
	{
		id = "342",
		name = "Poison Tail",
		type = PokemonTypes.POISON,
		power = "50",
		pp = "25",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		iscontact = true,
		summary = "Deals damage and has a 10% chance of poisoning the target. It also has an increased critical hit ratio. (+1 stage = 1/8 or 12.5%)",
	},
	{
		id = "343",
		name = "Covet",
		type = PokemonTypes.NORMAL,
		power = "40",
		pp = "40",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
		summary = "Steals the target's held item, if it has one. An item cannot be stolen if the target has Sticky Hold.",
	},
	{
		id = "344",
		name = "Volt Tackle",
		type = PokemonTypes.ELECTRIC,
		power = "120",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "The user receives recoil damage equal to 1/3 of the damage dealt.",
	},
	{
		id = "345",
		name = "Magical Leaf",
		type = PokemonTypes.GRASS,
		power = "60",
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and bypasses accuracy checks to always hit, unless the target is in the semi-invulnerable turn of a move such as Dig or Fly.",
	},
	{
		id = "346",
		name = "Water Sport",
		type = PokemonTypes.WATER,
		power = NOPOWER,
		pp = "15",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Reduces the power of Fire moves by 50% for all Pokemon in the battle. This effect last until the user switches out.",
	},
	{
		id = "347",
		name = "Calm Mind",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Raises the user's Special Attack and Special Defense stats by one stage each.",
	},
	{
		id = "348",
		name = "Leaf Blade",
		type = PokemonTypes.GRASS,
		power = "70",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		iscontact = true,
		summary = "Deals damage and has an increased critical hit ratio. (+1 stage = 1/8 or 12.5%)",
	},
	{
		id = "349",
		name = "Dragon Dance",
		type = PokemonTypes.DRAGON,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
		summary = "Raises the user's Attack stat and Speed stat by one stage each.",
	},
	{
		id = "350",
		name = "Rock Blast",
		type = PokemonTypes.ROCK,
		power = "25",
		pp = "10",
		accuracy = "80",
		category = MoveCategories.PHYSICAL,
		summary = "Hits 2-5 times in one turn. Odds: 37.5% / 37.5% / 12.5% / 12.5%",
	},
	{
		id = "351",
		name = "Shock Wave",
		type = PokemonTypes.ELECTRIC,
		power = "60",
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and bypasses accuracy checks to always hit, unless the target is in the semi-invulnerable turn of a move such as Dig or Fly.",
	},
	{
		id = "352",
		name = "Water Pulse",
		type = PokemonTypes.WATER,
		power = "60",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and has a 20% chance of confusing the target.",
	},
	{
		id = "353",
		name = "Doom Desire",
		type = PokemonTypes.STEEL,
		power = "120",
		pp = "5",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
		summary = "Locks in damage when used based on Atk of user and Def of target. After 2 turns, deals damage to the current enemy. Attack is typeless: cannot STAB, hits Wonder Guard.",
	},
	{
		id = "354",
		name = "Psycho Boost",
		type = PokemonTypes.PSYCHIC,
		power = "140",
		pp = "5",
		accuracy = "90",
		category = MoveCategories.SPECIAL,
		summary = "Deals damage and lowers the user's Special Attack stat by two stages.",
	}
}
