-- Move categories identify the type of attack a move is: physical, special, or status
MoveCategories = {
	NONE = 0,
	PHYSICAL = 1,
	SPECIAL = 2,
	STATUS = 3,
}

--List of pokemon types used to cycle through types when the Hidden Power button is clicked
HiddenPowerTypeList = {
	PokemonTypes.NORMAL,
	PokemonTypes.FIGHTING,
	PokemonTypes.FLYING,
	PokemonTypes.POISON,
	PokemonTypes.GROUND,
	PokemonTypes.ROCK,
	PokemonTypes.BUG,
	PokemonTypes.GHOST,
	PokemonTypes.STEEL,
	PokemonTypes.FIRE,
	PokemonTypes.WATER,
	PokemonTypes.GRASS,
	PokemonTypes.ELECTRIC,
	PokemonTypes.PSYCHIC,
	PokemonTypes.ICE,
	PokemonTypes.DRAGON,
	PokemonTypes.DARK
}

--Mapping of move types to move categories for gens 1-3
MoveTypeCategories = {
	[PokemonTypes.NORMAL] 	= MoveCategories.PHYSICAL,
	[PokemonTypes.FIGHTING]	= MoveCategories.PHYSICAL,
	[PokemonTypes.FLYING]	= MoveCategories.PHYSICAL,
	[PokemonTypes.POISON]	= MoveCategories.PHYSICAL,
	[PokemonTypes.GROUND]	= MoveCategories.PHYSICAL,
	[PokemonTypes.ROCK]		= MoveCategories.PHYSICAL,
	[PokemonTypes.BUG]		= MoveCategories.PHYSICAL,
	[PokemonTypes.GHOST]	= MoveCategories.PHYSICAL,
	[PokemonTypes.STEEL]	= MoveCategories.PHYSICAL,
	[PokemonTypes.FIRE]		= MoveCategories.SPECIAL,
	[PokemonTypes.WATER]	= MoveCategories.SPECIAL,
	[PokemonTypes.GRASS]	= MoveCategories.SPECIAL,
	[PokemonTypes.ELECTRIC]	= MoveCategories.SPECIAL,
	[PokemonTypes.PSYCHIC]	= MoveCategories.SPECIAL,
	[PokemonTypes.ICE]		= MoveCategories.SPECIAL,
	[PokemonTypes.DRAGON]	= MoveCategories.SPECIAL,
	[PokemonTypes.DARK]		= MoveCategories.SPECIAL,
}

NOPOWER = "---"
NOPP = ""

--[[
The various Pokémon moves (Gen 3)
Data pulled from Bulbapedia: https://bulbapedia.bulbagarden.net/wiki/List_of_moves (Note that categories differ from the source for Gen 3)

Format for an entry:

	id: string -> internal id of the move, represented as an integer in a string

	name: string -> the name of the move as it appears in game

	type: string -> the type of damage the move does, using the PokemonTypes enum

	power: string -> the strength of the move specified in game as in integer, or PLACEHOLDER when not applicable

	pp: string -> the base amount of actions this move is capable of

	accuracy: string -> the percent accuracy of the move connecting, or PLACEHOLDER when not applicable

	category: integer -> the type of damage a move does: physical/special/status, using the MoveCategories enum
]]
MoveData = {
	{ --- Empty entry for move ID 0
		id = "---",
		name = "---",
		type = "---",
		power = "",
		pp = NOPP,
		accuracy = "",
		category = MoveCategories.NONE,
	},
	{ -- Begin Gen 1 Moves
		id = "1",
		name = "Pound",
		type = PokemonTypes.NORMAL,
		power = "40",
		pp = "35",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "2",
		name = "Karate Chop",
		type = PokemonTypes.FIGHTING,
		power = "50",
		pp = "25",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "3",
		name = "DoubleSlap",
		type = PokemonTypes.NORMAL,
		power = "15",
		pp = "10",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "4",
		name = "Comet Punch",
		type = PokemonTypes.NORMAL,
		power = "18",
		pp = "15",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "5",
		name = "Mega Punch",
		type = PokemonTypes.NORMAL,
		power = "80",
		pp = "20",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "6",
		name = "Pay Day",
		type = PokemonTypes.NORMAL,
		power = "40",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "7",
		name = "Fire Punch",
		type = PokemonTypes.FIRE,
		power = "75",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "8",
		name = "Ice Punch",
		type = PokemonTypes.ICE,
		power = "75",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "9",
		name = "ThunderPunch",
		type = PokemonTypes.ELECTRIC,
		power = "75",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "10",
		name = "Scratch",
		type = PokemonTypes.NORMAL,
		power = "40",
		pp = "35",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "11",
		name = "ViceGrip",
		type = PokemonTypes.NORMAL,
		power = "55",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "12",
		name = "Guillotine",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = "30",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "13",
		name = "Razor Wind",
		type = PokemonTypes.NORMAL,
		power = "80",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "14",
		name = "Swords Dance",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "30",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "15",
		name = "Cut",
		type = PokemonTypes.NORMAL,
		power = "50",
		pp = "30",
		accuracy = "95",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "16",
		name = "Gust",
		type = PokemonTypes.FLYING,
		power = "40",
		pp = "35",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "17",
		name = "Wing Attack",
		type = PokemonTypes.FLYING,
		power = "60",
		pp = "35",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "18",
		name = "Whirlwind",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "19",
		name = "Fly",
		type = PokemonTypes.FLYING,
		power = "70",
		pp = "15",
		accuracy = "95",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "20",
		name = "Bind",
		type = PokemonTypes.NORMAL,
		power = "15",
		pp = "20",
		accuracy = "75",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "21",
		name = "Slam",
		type = PokemonTypes.NORMAL,
		power = "80",
		pp = "20",
		accuracy = "75",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "22",
		name = "Vine Whip",
		type = PokemonTypes.GRASS,
		power = "35",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "23",
		name = "Stomp",
		type = PokemonTypes.NORMAL,
		power = "65",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "24",
		name = "Double Kick",
		type = PokemonTypes.FIGHTING,
		power = "30",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "25",
		name = "Mega Kick",
		type = PokemonTypes.NORMAL,
		power = "120",
		pp = "5",
		accuracy = "75",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "26",
		name = "Jump Kick",
		type = PokemonTypes.FIGHTING,
		power = "70",
		pp = "25",
		accuracy = "95",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "27",
		name = "Rolling Kick",
		type = PokemonTypes.FIGHTING,
		power = "60",
		pp = "15",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "28",
		name = "Sand-Attack",
		type = PokemonTypes.GROUND,
		power = NOPOWER,
		pp = "15",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "29",
		name = "Headbutt",
		type = PokemonTypes.NORMAL,
		power = "70",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "30",
		name = "Horn Attack",
		type = PokemonTypes.NORMAL,
		power = "65",
		pp = "25",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "31",
		name = "Fury Attack",
		type = PokemonTypes.NORMAL,
		power = "15",
		pp = "20",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "32",
		name = "Horn Drill",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = "30",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "33",
		name = "Tackle",
		type = PokemonTypes.NORMAL,
		power = "35",
		pp = "35",
		accuracy = "95",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "34",
		name = "Body Slam",
		type = PokemonTypes.NORMAL,
		power = "85",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "35",
		name = "Wrap",
		type = PokemonTypes.NORMAL,
		power = "15",
		pp = "20",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "36",
		name = "Take Down",
		type = PokemonTypes.NORMAL,
		power = "90",
		pp = "20",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "37",
		name = "Thrash",
		type = PokemonTypes.NORMAL,
		power = "90",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "38",
		name = "Double-Edge",
		type = PokemonTypes.NORMAL,
		power = "120",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "39",
		name = "Tail Whip",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "30",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "40",
		name = "Poison Sting",
		type = PokemonTypes.POISON,
		power = "15",
		pp = "35",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "41",
		name = "Twineedle",
		type = PokemonTypes.BUG,
		power = "25",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "42",
		name = "Pin Missile",
		type = PokemonTypes.BUG,
		power = "14",
		pp = "20",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "43",
		name = "Leer",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "30",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "44",
		name = "Bite",
		type = PokemonTypes.DARK,
		power = "60",
		pp = "25",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "45",
		name = "Growl",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "40",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "46",
		name = "Roar",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "47",
		name = "Sing",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "15",
		accuracy = "55",
		category = MoveCategories.STATUS,
	},
	{
		id = "48",
		name = "Supersonic",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = "55",
		category = MoveCategories.STATUS,
	},
	{
		id = "49",
		name = "SonicBoom",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "50",
		name = "Disable",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = "55",
		category = MoveCategories.STATUS,
	},
	{
		id = "51",
		name = "Acid",
		type = PokemonTypes.POISON,
		power = "40",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "52",
		name = "Ember",
		type = PokemonTypes.FIRE,
		power = "40",
		pp = "25",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "53",
		name = "Flamethrower",
		type = PokemonTypes.FIRE,
		power = "95",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "54",
		name = "Mist",
		type = PokemonTypes.ICE,
		power = NOPOWER,
		pp = "30",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "55",
		name = "Water Gun",
		type = PokemonTypes.WATER,
		power = "40",
		pp = "25",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "56",
		name = "Hydro Pump",
		type = PokemonTypes.WATER,
		power = "120",
		pp = "5",
		accuracy = "80",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "57",
		name = "Surf",
		type = PokemonTypes.WATER,
		power = "95",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "58",
		name = "Ice Beam",
		type = PokemonTypes.ICE,
		power = "95",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "59",
		name = "Blizzard",
		type = PokemonTypes.ICE,
		power = "120",
		pp = "5",
		accuracy = "70",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "60",
		name = "Psybeam",
		type = PokemonTypes.PSYCHIC,
		power = "65",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "61",
		name = "BubbleBeam",
		type = PokemonTypes.WATER,
		power = "65",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "62",
		name = "Aurora Beam",
		type = PokemonTypes.ICE,
		power = "65",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "63",
		name = "Hyper Beam",
		type = PokemonTypes.NORMAL,
		power = "150",
		pp = "5",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "64",
		name = "Peck",
		type = PokemonTypes.FLYING,
		power = "35",
		pp = "35",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "65",
		name = "Drill Peck",
		type = PokemonTypes.FLYING,
		power = "80",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "66",
		name = "Submission",
		type = PokemonTypes.FIGHTING,
		power = "80",
		pp = "25",
		accuracy = "80",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "67",
		name = "Low Kick",
		type = PokemonTypes.FIGHTING,
		power = "WT",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "68",
		name = "Counter",
		type = PokemonTypes.FIGHTING,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "69",
		name = "Seismic Toss",
		type = PokemonTypes.FIGHTING,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "70",
		name = "Strength",
		type = PokemonTypes.NORMAL,
		power = "80",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "71",
		name = "Absorb",
		type = PokemonTypes.GRASS,
		power = "20",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "72",
		name = "Mega Drain",
		type = PokemonTypes.GRASS,
		power = "40",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "73",
		name = "Leech Seed",
		type = PokemonTypes.GRASS,
		power = NOPOWER,
		pp = "10",
		accuracy = "90",
		category = MoveCategories.STATUS,
	},
	{
		id = "74",
		name = "Growth",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "40",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "75",
		name = "Razor Leaf",
		type = PokemonTypes.GRASS,
		power = "55",
		pp = "25",
		accuracy = "95",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "76",
		name = "SolarBeam",
		type = PokemonTypes.GRASS,
		power = "120",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "77",
		name = "PoisonPowder",
		type = PokemonTypes.POISON,
		power = NOPOWER,
		pp = "35",
		accuracy = "75",
		category = MoveCategories.STATUS,
	},
	{
		id = "78",
		name = "Stun Spore",
		type = PokemonTypes.GRASS,
		power = NOPOWER,
		pp = "30",
		accuracy = "75",
		category = MoveCategories.STATUS,
	},
	{
		id = "79",
		name = "Sleep Powder",
		type = PokemonTypes.GRASS,
		power = NOPOWER,
		pp = "15",
		accuracy = "75",
		category = MoveCategories.STATUS,
	},
	{
		id = "80",
		name = "Petal Dance",
		type = PokemonTypes.GRASS,
		power = "70",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "81",
		name = "String Shot",
		type = PokemonTypes.BUG,
		power = NOPOWER,
		pp = "40",
		accuracy = "95",
		category = MoveCategories.STATUS,
	},
	{
		id = "82",
		name = "Dragon Rage",
		type = PokemonTypes.DRAGON,
		power = NOPOWER,
		pp = "10",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "83",
		name = "Fire Spin",
		type = PokemonTypes.FIRE,
		power = "15",
		pp = "15",
		accuracy = "70",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "84",
		name = "ThunderShock",
		type = PokemonTypes.ELECTRIC,
		power = "40",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "85",
		name = "Thunderbolt",
		type = PokemonTypes.ELECTRIC,
		power = "95",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "86",
		name = "Thunder Wave",
		type = PokemonTypes.ELECTRIC,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "87",
		name = "Thunder",
		type = PokemonTypes.ELECTRIC,
		power = "120",
		pp = "10",
		accuracy = "70",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "88",
		name = "Rock Throw",
		type = PokemonTypes.ROCK,
		power = "50",
		pp = "15",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "89",
		name = "Earthquake",
		type = PokemonTypes.GROUND,
		power = "100",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "90",
		name = "Fissure",
		type = PokemonTypes.GROUND,
		power = NOPOWER,
		pp = "5",
		accuracy = "30",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "91",
		name = "Dig",
		type = PokemonTypes.GROUND,
		power = "60",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "92",
		name = "Toxic",
		type = PokemonTypes.POISON,
		power = NOPOWER,
		pp = "10",
		accuracy = "85",
		category = MoveCategories.STATUS,
	},
	{
		id = "93",
		name = "Confusion",
		type = PokemonTypes.PSYCHIC,
		power = "50",
		pp = "25",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "94",
		name = "Psychic",
		type = PokemonTypes.PSYCHIC,
		power = "90",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "95",
		name = "Hypnosis",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "20",
		accuracy = "60",
		category = MoveCategories.STATUS,
	},
	{
		id = "96",
		name = "Meditate",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "40",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "97",
		name = "Agility",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "30",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "98",
		name = "Quick Attack",
		type = PokemonTypes.NORMAL,
		power = "40",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "99",
		name = "Rage",
		type = PokemonTypes.NORMAL,
		power = "20",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "100",
		name = "Teleport",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "101",
		name = "Night Shade",
		type = PokemonTypes.GHOST,
		power = NOPOWER,
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "102",
		name = "Mimic",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "103",
		name = "Screech",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "40",
		accuracy = "85",
		category = MoveCategories.STATUS,
	},
	{
		id = "104",
		name = "Double Team",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "15",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "105",
		name = "Recover",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "106",
		name = "Harden",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "30",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "107",
		name = "Minimize",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "108",
		name = "SmokeScreen",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "109",
		name = "Confuse Ray",
		type = PokemonTypes.GHOST,
		power = NOPOWER,
		pp = "10",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "110",
		name = "Withdraw",
		type = PokemonTypes.WATER,
		power = NOPOWER,
		pp = "40",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "111",
		name = "Defense Curl",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "40",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "112",
		name = "Barrier",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "30",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "113",
		name = "Light Screen",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "30",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "114",
		name = "Haze",
		type = PokemonTypes.ICE,
		power = NOPOWER,
		pp = "30",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "115",
		name = "Reflect",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "116",
		name = "Focus Energy",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "30",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "117",
		name = "Bide",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "118",
		name = "Metronome",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "119",
		name = "Mirror Move",
		type = PokemonTypes.FLYING,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "120",
		name = "Selfdestruct",
		type = PokemonTypes.NORMAL,
		power = "200",
		pp = "5",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "121",
		name = "Egg Bomb",
		type = PokemonTypes.NORMAL,
		power = "100",
		pp = "10",
		accuracy = "75",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "122",
		name = "Lick",
		type = PokemonTypes.GHOST,
		power = "20",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "123",
		name = "Smog",
		type = PokemonTypes.POISON,
		power = "20",
		pp = "20",
		accuracy = "70",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "124",
		name = "Sludge",
		type = PokemonTypes.POISON,
		power = "65",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "125",
		name = "Bone Club",
		type = PokemonTypes.GROUND,
		power = "65",
		pp = "20",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "126",
		name = "Fire Blast",
		type = PokemonTypes.FIRE,
		power = "120",
		pp = "5",
		accuracy = "85",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "127",
		name = "Waterfall",
		type = PokemonTypes.WATER,
		power = "80",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "128",
		name = "Clamp",
		type = PokemonTypes.WATER,
		power = "35",
		pp = "10",
		accuracy = "75",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "129",
		name = "Swift",
		type = PokemonTypes.NORMAL,
		power = "60",
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "130",
		name = "Skull Bash",
		type = PokemonTypes.NORMAL,
		power = "100",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "131",
		name = "Spike Cannon",
		type = PokemonTypes.NORMAL,
		power = "20",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "132",
		name = "Constrict",
		type = PokemonTypes.NORMAL,
		power = "10",
		pp = "35",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "133",
		name = "Amnesia",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "134",
		name = "Kinesis",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "15",
		accuracy = "80",
		category = MoveCategories.STATUS,
	},
	{
		id = "135",
		name = "Softboiled",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "136",
		name = "Hi Jump Kick",
		type = PokemonTypes.FIGHTING,
		power = "85",
		pp = "20",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "137",
		name = "Glare",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "30",
		accuracy = "75",
		category = MoveCategories.STATUS,
	},
	{
		id = "138",
		name = "Dream Eater",
		type = PokemonTypes.PSYCHIC,
		power = "100",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "139",
		name = "Poison Gas",
		type = PokemonTypes.POISON,
		power = NOPOWER,
		pp = "40",
		accuracy = "55",
		category = MoveCategories.STATUS,
	},
	{
		id = "140",
		name = "Barrage",
		type = PokemonTypes.NORMAL,
		power = "15",
		pp = "20",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "141",
		name = "Leech Life",
		type = PokemonTypes.BUG,
		power = "20",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "142",
		name = "Lovely Kiss",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = "75",
		category = MoveCategories.STATUS,
	},
	{
		id = "143",
		name = "Sky Attack",
		type = PokemonTypes.FLYING,
		power = "140",
		pp = "5",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "144",
		name = "Transform",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "145",
		name = "Bubble",
		type = PokemonTypes.WATER,
		power = "20",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "146",
		name = "Dizzy Punch",
		type = PokemonTypes.NORMAL,
		power = "70",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "147",
		name = "Spore",
		type = PokemonTypes.GRASS,
		power = NOPOWER,
		pp = "15",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "148",
		name = "Flash",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = "70",
		category = MoveCategories.STATUS,
	},
	{
		id = "149",
		name = "Psywave",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "15",
		accuracy = "80",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "150",
		name = "Splash",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "40",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "151",
		name = "Acid Armor",
		type = PokemonTypes.POISON,
		power = NOPOWER,
		pp = "40",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "152",
		name = "Crabhammer",
		type = PokemonTypes.WATER,
		power = "90",
		pp = "10",
		accuracy = "85",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "153",
		name = "Explosion",
		type = PokemonTypes.NORMAL,
		power = "250",
		pp = "5",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "154",
		name = "Fury Swipes",
		type = PokemonTypes.NORMAL,
		power = "18",
		pp = "15",
		accuracy = "80",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "155",
		name = "Bonemerang",
		type = PokemonTypes.GROUND,
		power = "50",
		pp = "10",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "156",
		name = "Rest",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "157",
		name = "Rock Slide",
		type = PokemonTypes.ROCK,
		power = "75",
		pp = "10",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "158",
		name = "Hyper Fang",
		type = PokemonTypes.NORMAL,
		power = "80",
		pp = "15",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "159",
		name = "Sharpen",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "30",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "160",
		name = "Conversion",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "30",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "161",
		name = "Tri Attack",
		type = PokemonTypes.NORMAL,
		power = "80",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "162",
		name = "Super Fang",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "163",
		name = "Slash",
		type = PokemonTypes.NORMAL,
		power = "70",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "164",
		name = "Substitute",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "165",
		name = "Struggle",
		type = PokemonTypes.NORMAL,
		power = "50",
		pp = "1",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{ -- Begin Gen 2 Moves
		id = "166",
		name = "Sketch",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "1",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "167",
		name = "Triple Kick",
		type = PokemonTypes.FIGHTING,
		power = "10",
		pp = "10",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "168",
		name = "Thief",
		type = PokemonTypes.DARK,
		power = "40",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "169",
		name = "Spider Web",
		type = PokemonTypes.BUG,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "170",
		name = "Mind Reader",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "171",
		name = "Nightmare",
		type = PokemonTypes.GHOST,
		power = NOPOWER,
		pp = "15",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "172",
		name = "Flame Wheel",
		type = PokemonTypes.FIRE,
		power = "60",
		pp = "25",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "173",
		name = "Snore",
		type = PokemonTypes.NORMAL,
		power = "40",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "174",
		name = "Curse",
		type = PokemonTypes.UNKNOWN,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "175",
		name = "Flail",
		type = PokemonTypes.NORMAL,
		power = "<HP",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "176",
		name = "Conversion 2",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "30",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "177",
		name = "Aeroblast",
		type = PokemonTypes.FLYING,
		power = "100",
		pp = "5",
		accuracy = "95",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "178",
		name = "Cotton Spore",
		type = PokemonTypes.GRASS,
		power = NOPOWER,
		pp = "40",
		accuracy = "85",
		category = MoveCategories.STATUS,
	},
	{
		id = "179",
		name = "Reversal",
		type = PokemonTypes.FIGHTING,
		power = "<HP",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "180",
		name = "Spite",
		type = PokemonTypes.GHOST,
		power = NOPOWER,
		pp = "10",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "181",
		name = "Powder Snow",
		type = PokemonTypes.ICE,
		power = "40",
		pp = "25",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "182",
		name = "Protect",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "183",
		name = "Mach Punch",
		type = PokemonTypes.FIGHTING,
		power = "40",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "184",
		name = "Scary Face",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = "90",
		category = MoveCategories.STATUS,
	},
	{
		id = "185",
		name = "Faint Attack",
		type = PokemonTypes.DARK,
		power = "60",
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.SPECIAL,
	},
	{
		id = "186",
		name = "Sweet Kiss",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = "75",
		category = MoveCategories.STATUS,
	},
	{
		id = "187",
		name = "Belly Drum",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "188",
		name = "Sludge Bomb",
		type = PokemonTypes.POISON,
		power = "90",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "189",
		name = "Mud-Slap",
		type = PokemonTypes.GROUND,
		power = "20",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "190",
		name = "Octazooka",
		type = PokemonTypes.WATER,
		power = "65",
		pp = "10",
		accuracy = "85",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "191",
		name = "Spikes",
		type = PokemonTypes.GROUND,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "192",
		name = "Zap Cannon",
		type = PokemonTypes.ELECTRIC,
		power = "100",
		pp = "5",
		accuracy = "50",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "193",
		name = "Foresight",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "40",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "194",
		name = "Destiny Bond",
		type = PokemonTypes.GHOST,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "195",
		name = "Perish Song",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "196",
		name = "Icy Wind",
		type = PokemonTypes.ICE,
		power = "55",
		pp = "15",
		accuracy = "95",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "197",
		name = "Detect",
		type = PokemonTypes.FIGHTING,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "198",
		name = "Bone Rush",
		type = PokemonTypes.GROUND,
		power = "25",
		pp = "10",
		accuracy = "80",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "199",
		name = "Lock-On",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "200",
		name = "Outrage",
		type = PokemonTypes.DRAGON,
		power = "90",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "201",
		name = "Sandstorm",
		type = PokemonTypes.ROCK,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "202",
		name = "Giga Drain",
		type = PokemonTypes.GRASS,
		power = "60",
		pp = "5",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "203",
		name = "Endure",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "204",
		name = "Charm",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "205",
		name = "Rollout",
		type = PokemonTypes.ROCK,
		power = "30",
		pp = "20",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "206",
		name = "False Swipe",
		type = PokemonTypes.NORMAL,
		power = "40",
		pp = "40",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "207",
		name = "Swagger",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "15",
		accuracy = "90",
		category = MoveCategories.STATUS,
	},
	{
		id = "208",
		name = "Milk Drink",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "209",
		name = "Spark",
		type = PokemonTypes.ELECTRIC,
		power = "65",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "210",
		name = "Fury Cutter",
		type = PokemonTypes.BUG,
		power = "10",
		pp = "20",
		accuracy = "95",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "211",
		name = "Steel Wing",
		type = PokemonTypes.STEEL,
		power = "70",
		pp = "25",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "212",
		name = "Mean Look",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "213",
		name = "Attract",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "15",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "214",
		name = "Sleep Talk",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "215",
		name = "Heal Bell",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "216",
		name = "Return",
		type = PokemonTypes.NORMAL,
		power = ">FR",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "217",
		name = "Present",
		type = PokemonTypes.NORMAL,
		power = "RNG",
		pp = "15",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "218",
		name = "Frustration",
		type = PokemonTypes.NORMAL,
		power = "<FR",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "219",
		name = "Safeguard",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "25",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "220",
		name = "Pain Split",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "221",
		name = "Sacred Fire",
		type = PokemonTypes.FIRE,
		power = "100",
		pp = "5",
		accuracy = "95",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "222",
		name = "Magnitude",
		type = PokemonTypes.GROUND,
		power = "RNG",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "223",
		name = "DynamicPunch",
		type = PokemonTypes.FIGHTING,
		power = "100",
		pp = "5",
		accuracy = "50",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "224",
		name = "Megahorn",
		type = PokemonTypes.BUG,
		power = "120",
		pp = "10",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "225",
		name = "DragonBreath",
		type = PokemonTypes.DRAGON,
		power = "60",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "226",
		name = "Baton Pass",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "40",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "227",
		name = "Encore",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "228",
		name = "Pursuit",
		type = PokemonTypes.DARK,
		power = "40",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "229",
		name = "Rapid Spin",
		type = PokemonTypes.NORMAL,
		power = "20",
		pp = "40",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "230",
		name = "Sweet Scent",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "231",
		name = "Iron Tail",
		type = PokemonTypes.STEEL,
		power = "100",
		pp = "15",
		accuracy = "75",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "232",
		name = "Metal Claw",
		type = PokemonTypes.STEEL,
		power = "50",
		pp = "35",
		accuracy = "95",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "233",
		name = "Vital Throw",
		type = PokemonTypes.FIGHTING,
		power = "70",
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "234",
		name = "Morning Sun",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "235",
		name = "Synthesis",
		type = PokemonTypes.GRASS,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "236",
		name = "Moonlight",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "237",
		name = "Hidden Power",
		type = PokemonTypes.NORMAL,
		power = "VAR",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "238",
		name = "Cross Chop",
		type = PokemonTypes.FIGHTING,
		power = "100",
		pp = "5",
		accuracy = "80",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "239",
		name = "Twister",
		type = PokemonTypes.DRAGON,
		power = "40",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "240",
		name = "Rain Dance",
		type = PokemonTypes.WATER,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "241",
		name = "Sunny Day",
		type = PokemonTypes.FIRE,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "242",
		name = "Crunch",
		type = PokemonTypes.DARK,
		power = "80",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "243",
		name = "Mirror Coat",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "244",
		name = "Psych Up",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "245",
		name = "ExtremeSpeed",
		type = PokemonTypes.NORMAL,
		power = "80",
		pp = "5",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "246",
		name = "AncientPower",
		type = PokemonTypes.ROCK,
		power = "60",
		pp = "5",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "247",
		name = "Shadow Ball",
		type = PokemonTypes.GHOST,
		power = "80",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "248",
		name = "Future Sight",
		type = PokemonTypes.PSYCHIC,
		power = "80",
		pp = "15",
		accuracy = "90",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "249",
		name = "Rock Smash",
		type = PokemonTypes.FIGHTING,
		power = "20",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "250",
		name = "Whirlpool",
		type = PokemonTypes.WATER,
		power = "15",
		pp = "15",
		accuracy = "70",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "251",
		name = "Beat Up",
		type = PokemonTypes.DARK,
		power = "10",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{ -- Begin Gen 3 Moves
		id = "252",
		name = "Fake Out",
		type = PokemonTypes.NORMAL,
		power = "40",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "253",
		name = "Uproar",
		type = PokemonTypes.NORMAL,
		power = "50",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "254",
		name = "Stockpile",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "255",
		name = "Spit Up",
		type = PokemonTypes.NORMAL,
		power = "100x",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "256",
		name = "Swallow",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "257",
		name = "Heat Wave",
		type = PokemonTypes.FIRE,
		power = "100",
		pp = "10",
		accuracy = "90",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "258",
		name = "Hail",
		type = PokemonTypes.ICE,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "259",
		name = "Torment",
		type = PokemonTypes.DARK,
		power = NOPOWER,
		pp = "15",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "260",
		name = "Flatter",
		type = PokemonTypes.DARK,
		power = NOPOWER,
		pp = "15",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "261",
		name = "Will-O-Wisp",
		type = PokemonTypes.FIRE,
		power = NOPOWER,
		pp = "15",
		accuracy = "75",
		category = MoveCategories.STATUS,
	},
	{
		id = "262",
		name = "Memento",
		type = PokemonTypes.DARK,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "263",
		name = "Facade",
		type = PokemonTypes.NORMAL,
		power = "70",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "264",
		name = "Focus Punch",
		type = PokemonTypes.FIGHTING,
		power = "150",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "265",
		name = "SmellingSalt",
		type = PokemonTypes.NORMAL,
		power = "60",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "266",
		name = "Follow Me",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "267",
		name = "Nature Power",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "268",
		name = "Charge",
		type = PokemonTypes.ELECTRIC,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "269",
		name = "Taunt",
		type = PokemonTypes.DARK,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "270",
		name = "Helping Hand",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "271",
		name = "Trick",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "10",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "272",
		name = "Role Play",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "273",
		name = "Wish",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "274",
		name = "Assist",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "275",
		name = "Ingrain",
		type = PokemonTypes.GRASS,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "276",
		name = "Superpower",
		type = PokemonTypes.FIGHTING,
		power = "120",
		pp = "5",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "277",
		name = "Magic Coat",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "15",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "278",
		name = "Recycle",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "279",
		name = "Revenge",
		type = PokemonTypes.FIGHTING,
		power = "60",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "280",
		name = "Brick Break",
		type = PokemonTypes.FIGHTING,
		power = "75",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "281",
		name = "Yawn",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "282",
		name = "Knock Off",
		type = PokemonTypes.DARK,
		power = "20",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "283",
		name = "Endeavor",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "284",
		name = "Eruption",
		type = PokemonTypes.FIRE,
		power = ">HP",
		pp = "5",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "285",
		name = "Skill Swap",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "286",
		name = "Imprison",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "287",
		name = "Refresh",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "288",
		name = "Grudge",
		type = PokemonTypes.GHOST,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "289",
		name = "Snatch",
		type = PokemonTypes.DARK,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "290",
		name = "Secret Power",
		type = PokemonTypes.NORMAL,
		power = "70",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "291",
		name = "Dive",
		type = PokemonTypes.WATER,
		power = "60",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "292",
		name = "Arm Thrust",
		type = PokemonTypes.FIGHTING,
		power = "15",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "293",
		name = "Camouflage",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "294",
		name = "Tail Glow",
		type = PokemonTypes.BUG,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "295",
		name = "Luster Purge",
		type = PokemonTypes.PSYCHIC,
		power = "70",
		pp = "5",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "296",
		name = "Mist Ball",
		type = PokemonTypes.PSYCHIC,
		power = "70",
		pp = "5",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "297",
		name = "FeatherDance",
		type = PokemonTypes.FLYING,
		power = NOPOWER,
		pp = "15",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "298",
		name = "Teeter Dance",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "299",
		name = "Blaze Kick",
		type = PokemonTypes.FIRE,
		power = "85",
		pp = "10",
		accuracy = "90",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "300",
		name = "Mud Sport",
		type = PokemonTypes.GROUND,
		power = NOPOWER,
		pp = "15",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "301",
		name = "Ice Ball",
		type = PokemonTypes.ICE,
		power = "30",
		pp = "20",
		accuracy = "90",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "302",
		name = "Needle Arm",
		type = PokemonTypes.GRASS,
		power = "60",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "303",
		name = "Slack Off",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "10",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "304",
		name = "Hyper Voice",
		type = PokemonTypes.NORMAL,
		power = "90",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "305",
		name = "Poison Fang",
		type = PokemonTypes.POISON,
		power = "50",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "306",
		name = "Crush Claw",
		type = PokemonTypes.NORMAL,
		power = "75",
		pp = "10",
		accuracy = "95",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "307",
		name = "Blast Burn",
		type = PokemonTypes.FIRE,
		power = "150",
		pp = "5",
		accuracy = "90",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "308",
		name = "Hydro Cannon",
		type = PokemonTypes.WATER,
		power = "150",
		pp = "5",
		accuracy = "90",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "309",
		name = "Meteor Mash",
		type = PokemonTypes.STEEL,
		power = "100",
		pp = "10",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "310",
		name = "Astonish",
		type = PokemonTypes.GHOST,
		power = "30",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "311",
		name = "Weather Ball",
		type = PokemonTypes.NORMAL,
		power = "50",
		pp = "10",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "312",
		name = "Aromatherapy",
		type = PokemonTypes.GRASS,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "313",
		name = "Fake Tears",
		type = PokemonTypes.DARK,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "314",
		name = "Air Cutter",
		type = PokemonTypes.FLYING,
		power = "55",
		pp = "25",
		accuracy = "95",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "315",
		name = "Overheat",
		type = PokemonTypes.FIRE,
		power = "140",
		pp = "5",
		accuracy = "90",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "316",
		name = "Odor Sleuth",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "40",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "317",
		name = "Rock Tomb",
		type = PokemonTypes.ROCK,
		power = "50",
		pp = "10",
		accuracy = "80",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "318",
		name = "Silver Wind",
		type = PokemonTypes.BUG,
		power = "60",
		pp = "5",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "319",
		name = "Metal Sound",
		type = PokemonTypes.STEEL,
		power = NOPOWER,
		pp = "40",
		accuracy = "85",
		category = MoveCategories.STATUS,
	},
	{
		id = "320",
		name = "GrassWhistle",
		type = PokemonTypes.GRASS,
		power = NOPOWER,
		pp = "15",
		accuracy = "55",
		category = MoveCategories.STATUS,
	},
	{
		id = "321",
		name = "Tickle",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "20",
		accuracy = "100",
		category = MoveCategories.STATUS,
	},
	{
		id = "322",
		name = "Cosmic Power",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "323",
		name = "Water Spout",
		type = PokemonTypes.WATER,
		power = ">HP",
		pp = "5",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "324",
		name = "Signal Beam",
		type = PokemonTypes.BUG,
		power = "75",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "325",
		name = "Shadow Punch",
		type = PokemonTypes.GHOST,
		power = "60",
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "326",
		name = "Extrasensory",
		type = PokemonTypes.PSYCHIC,
		power = "80",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "327",
		name = "Sky Uppercut",
		type = PokemonTypes.FIGHTING,
		power = "85",
		pp = "15",
		accuracy = "90",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "328",
		name = "Sand Tomb",
		type = PokemonTypes.GROUND,
		power = "15",
		pp = "15",
		accuracy = "70",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "329",
		name = "Sheer Cold",
		type = PokemonTypes.ICE,
		power = NOPOWER,
		pp = "5",
		accuracy = "30",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "330",
		name = "Muddy Water",
		type = PokemonTypes.WATER,
		power = "95",
		pp = "10",
		accuracy = "85",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "331",
		name = "Bullet Seed",
		type = PokemonTypes.GRASS,
		power = "10",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "332",
		name = "Aerial Ace",
		type = PokemonTypes.FLYING,
		power = "60",
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "333",
		name = "Icicle Spear",
		type = PokemonTypes.ICE,
		power = "10",
		pp = "30",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "334",
		name = "Iron Defense",
		type = PokemonTypes.STEEL,
		power = NOPOWER,
		pp = "15",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "335",
		name = "Block",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "5",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "336",
		name = "Howl",
		type = PokemonTypes.NORMAL,
		power = NOPOWER,
		pp = "40",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "337",
		name = "Dragon Claw",
		type = PokemonTypes.DRAGON,
		power = "80",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "338",
		name = "Frenzy Plant",
		type = PokemonTypes.GRASS,
		power = "150",
		pp = "5",
		accuracy = "90",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "339",
		name = "Bulk Up",
		type = PokemonTypes.FIGHTING,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "340",
		name = "Bounce",
		type = PokemonTypes.FLYING,
		power = "85",
		pp = "5",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "341",
		name = "Mud Shot",
		type = PokemonTypes.GROUND,
		power = "55",
		pp = "15",
		accuracy = "95",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "342",
		name = "Poison Tail",
		type = PokemonTypes.POISON,
		power = "50",
		pp = "25",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "343",
		name = "Covet",
		type = PokemonTypes.NORMAL,
		power = "40",
		pp = "40",
		accuracy = "100",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "344",
		name = "Volt Tackle",
		type = PokemonTypes.ELECTRIC,
		power = "120",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "345",
		name = "Magical Leaf",
		type = PokemonTypes.GRASS,
		power = "60",
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.SPECIAL,
	},
	{
		id = "346",
		name = "Water Sport",
		type = PokemonTypes.WATER,
		power = NOPOWER,
		pp = "15",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "347",
		name = "Calm Mind",
		type = PokemonTypes.PSYCHIC,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "348",
		name = "Leaf Blade",
		type = PokemonTypes.GRASS,
		power = "70",
		pp = "15",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "349",
		name = "Dragon Dance",
		type = PokemonTypes.DRAGON,
		power = NOPOWER,
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.STATUS,
	},
	{
		id = "350",
		name = "Rock Blast",
		type = PokemonTypes.ROCK,
		power = "25",
		pp = "10",
		accuracy = "80",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "351",
		name = "Shock Wave",
		type = PokemonTypes.ELECTRIC,
		power = "60",
		pp = "20",
		accuracy = PLACEHOLDER,
		category = MoveCategories.SPECIAL,
	},
	{
		id = "352",
		name = "Water Pulse",
		type = PokemonTypes.WATER,
		power = "60",
		pp = "20",
		accuracy = "100",
		category = MoveCategories.SPECIAL,
	},
	{
		id = "353",
		name = "Doom Desire",
		type = PokemonTypes.STEEL,
		power = "120",
		pp = "5",
		accuracy = "85",
		category = MoveCategories.PHYSICAL,
	},
	{
		id = "354",
		name = "Psycho Boost",
		type = PokemonTypes.PSYCHIC,
		power = "140",
		pp = "5",
		accuracy = "90",
		category = MoveCategories.SPECIAL,
	}
}
